Add missing translations for dossiercover.
4teamwork/opengever.core pull request #6607
Opened 2020-08-31 05:46 UTC by 2e12

To display a French translation, it was added when exporting Dossiercover.

_PR-Description: should contain all the information necessary for an outsider to understand the change without looking at the code or the issue!_

- _Why the change is necessary_
- _What the goal of the change is_
- _How change is achieved (e.g. design decisions)_
- _The author should advertise and sell the change in the PR body_

_Screenshot: whenever useful, but only as a visual aid._

Definition of Done: https://4teamwork.atlassian.net/wiki/spaces/CHX4TW/pages/917562/

## Checklist (Must have)

_Everything has to be done/checked. Checked but not present means the author deemed it unnecessary._

- [ ] Changelog entry
- [ ] Link to issue (Jira or GitHub) and backlink in issue (Jira)

## Checklist (if applicable)

_Only applicable should be left and checked._

- API change:
  - [ ] Documentation is updated
  - If breaking:
    - [ ] api-change label added
    - [ ] Scrum master is informed
- New functionality:
  - [ ] for `document` also works for `mail`
  - [ ] for `task` also works for `forwarding`
- Upgrade steps (changes in profile):
  - [ ] Make it deferrable if possible
  - [ ] Execute as much as possible conditionally
- DB-Schema migration
  - [ ] All changes on a model (columns, etc) are included in a DB-schema migration.
  - [ ] Constraint names are shorter than 30 characters (`Oracle`)
- [ ] Change could impact client installations, client policies need to be adapted
- New translations
  - [ ] All msg-strings are unicode
- Change in schema definition:
  - [ ] If `missing_value` is specified, then `default` has to be set to the same value

2020-09-29 15:50 UTC, njohner requested changes
Over LGTM, but I think you took a bit of a convoluted approach, see my comment. Also, try to make your commit message titles a bit more explicit. You also have some typos in the commit messages, notably `is'nt` should be `isn't`

2020-09-29 15:50 UTC, njohner commented on opengever/latex/dossiercover.py
> +        return self.get_dossier_metadata()
I'm not a fan of this method that just proxies to another method. What's the point?

2020-09-29 15:50 UTC, njohner commented on opengever/latex/dossiercover.py
> +    def get_metadata_config(self):
The naming is a bit weird to me. How is that a config?

2020-09-29 15:50 UTC, njohner commented on opengever/latex/dossiercover.py
> +                args[key] = u'{}: {}'.format(item['label'], item['value'])
I find that whole thing pretty convoluted. First you set labels for all the metadata, then when it's an empty string you get rid of it.
Moreover I feel like you are doing the template's job here. Why not simply add the few missing labels to the original missing `args` dictionary you had? You did not make the code less complex and you did not make the code shorter, so what did you gain?
I'd either simply add 'responsible_label', `start_label` and so on to `args` or I'd go maybe for something like:
```
    translatable_labels = {
        'responsible_label': _('label_responsible', default='Responsible')
    }
    def get_render_arguments(self):
        args = self.get_dossier_metadata()
        args.update(self.get_metadata_labels())
  
    def get_translated_labels(self):
        args = {}
        for key, label in self.translatable_labels.items():
              args[key] = translate(label, context=self.request)
        return args
```

But again the simplest solution of adding the needed labels in `args` might even be easier to read

2020-09-29 15:50 UTC, njohner commented on opengever/latex/templates/dossiercover.tex
> +\textbf{${referencenr}}\newline
and here you would have:
`\textbf{${referencenr_label}: ${referencenr}}\newline`

2020-09-29 15:50 UTC, njohner commented on opengever/latex/tests/test_default_layout.py
>          self.assertEqual(layout.get_render_arguments(), args)
`assertDictEqual` would be better

2020-09-30 05:00 UTC, 2e12 commented
@njohner Thank you for your feedback.I tried to make it as similar as possible to [dossierdetails.py,](https://github.com/4teamwork/opengever.core/blob/master/opengever/latex/dossierdetails.py) which is why the code is the way it is. But I can understand your feedback and I will adapt my changes accordingly.

2020-09-30 12:11 UTC, njohner approved these changes
LGTM

2020-10-01 08:13 UTC, merged