Nj/530 manage local groups
4teamwork/opengever.core pull request #6631
Opened 2020-09-11 06:28 UTC by njohner

_PR-Description: should contain all the information necessary for an outsider to understand the change without looking at the code or the issue!_

- _Why the change is necessary_
- _What the goal of the change is_
- _How change is achieved (e.g. design decisions)_
- _The author should advertise and sell the change in the PR body_

_Screenshot: whenever useful, but only as a visual aid._

Definition of Done: https://4teamwork.atlassian.net/wiki/spaces/CHX4TW/pages/917562/

## Checklist (Must have)

_Everything has to be done/checked. Checked but not present means the author deemed it unnecessary._

- [ ] Changelog entry
- [ ] Link to issue (Jira or GitHub) and backlink in issue (Jira)

## Checklist (if applicable)

_Only applicable should be left and checked._

- API change:
  - [ ] Documentation is updated
  - If breaking:
    - [ ] api-change label added
    - [ ] Scrum master is informed
- New functionality:
  - [ ] for `document` also works for `mail`
  - [ ] for `task` also works for `forwarding`
- Upgrade steps (changes in profile):
  - [ ] Make it deferrable if possible
  - [ ] Execute as much as possible conditionally
- DB-Schema migration
  - [ ] All changes on a model (columns, etc) are included in a DB-schema migration.
  - [ ] Constraint names are shorter than 30 characters (`Oracle`)
- [ ] Change could impact client installations, client policies need to be adapted
- New translations
  - [ ] All msg-strings are unicode
- Change in schema definition:
  - [ ] If `missing_value` is specified, then `default` has to be set to the same value

2020-09-22 08:41 UTC, lukasgraf requested changes
LGTM 👍 
Just some minor nitpicks, and the changes we discussed to not deactivate GroupManagement for the LDAP plugin, but instead change the upgrade step to move `source_groups` to the top, and assert on its position where appropriate.

2020-09-22 08:41 UTC, lukasgraf commented on opengever/api/tests/test_group.py
> +    def test_cannot_update_group_with_dissallowed_roles(self, browser):
-> `disallowed`

2020-09-22 08:41 UTC, lukasgraf commented on opengever/api/group.py
>          delete_successful = portal_groups.removeGroup(self._get_group_id)
I'm wondering why this doesn't require elevated privileges, like PATCH does...

2020-09-22 08:41 UTC, lukasgraf commented on opengever/ogds/base/sync/ogds_updater.py
> +        for group in session.query(Group).filter(Group.is_local != true()):
I believe it should be possible to just replace the SQLAlchemy expression `true()` with Python `True` here, and let SQLAlchemy deal with type casting from Python to SQL.

2020-09-22 08:41 UTC, lukasgraf commented on opengever/ogds/base/sync/ogds_updater.py
> +                        u"Skipping group '{}'! "
-> `Skipping LDAP group ...` to make it even more clear what's happening?

2020-09-22 08:41 UTC, lukasgraf commented on docs/public/dev-manual/api/users.rst
> +Gruppen erstellen, modifizieren und löschen kann über den `@groups` Endpoint gemacht werden und ist in der `plone.restapi Dokumentation <https://plonerestapi.readthedocs.io/en/latest/groups.html>`_ b
Double backticks around `@groups` and other literals below instead of single ones ;)

2020-09-22 08:41 UTC, lukasgraf commented on docs/public/dev-manual/api/users.rst
> +- Die Gruppen Daten werden korrekt im OGDS abgespiegelt.
If you lead in with `so dass`, the sentence order for these bullet points would need to be so that the verbs are at the end of the sentence. I would simply change the line above to `Dieser Endpoint wurde für GEVER folgendermassen angepasst:`, then it works 😉

2020-09-22 08:41 UTC, lukasgraf commented on docs/public/dev-manual/api/users.rst
> +- Gruppennamen kann nicht länger als 255 Charakter lang sein
kann -> darf, Charakter -> Zeichen

2020-09-22 08:41 UTC, lukasgraf commented on opengever/core/upgrades/20200921135157_manage_groups_with_source_groups_plugin/upgrade.py
> +            plugins.deactivatePlugin(IGroupManagement, 'ldap')
As discussed, we decided to not deactivate GroupManagement for the LDAP plugin, right?

2020-09-22 09:29 UTC, njohner commented on opengever/api/group.py
> +        self.group_id = self._get_group_id
Yes I agree, but `_get_group_id` is defined in the plone restapi as a property for this endpoint and I wanted to rather use group_id, as I also do for the `Delete` endpoint. I'll change `_get_group_id` to `get_group_id` and make it a method instead of a property

2020-09-22 09:31 UTC, lukasgraf commented on opengever/api/group.py
> +        self.group_id = self._get_group_id
@njohner ah, I see, didn't realize that. Then I would actually leave it as-is, for ease of diffing changes with upstream in the future.

2020-09-22 09:39 UTC, njohner commented on opengever/api/group.py
> +        self.group_id = self._get_group_id
Ok I removed the assignment to `self.group_id` instead

2020-09-22 12:28 UTC, njohner commented on opengever/api/group.py
>          delete_successful = portal_groups.removeGroup(self._get_group_id)
It seems that only the `addMember` and `removeMember` from groups need elevated privileges

2020-09-22 15:26 UTC, njohner commented on opengever/api/group.py
>          delete_successful = portal_groups.removeGroup(self._get_group_id)
I've corrected the POST endpoint accordingly

2020-09-24 15:24 UTC, njohner commented on opengever/core/upgrades/20200921135157_manage_groups_with_source_groups_plugin/upgrade.py
> +            plugins.deactivatePlugin(IGroupManagement, 'ldap')
I changed the upgrade step to activate the `source_groups` plugin for group enumeration and management and that it comes first for group management.
I also check those conditions in the `@groups` endpoint and in the `sync_ogds`

2020-09-24 15:24 UTC, njohner commented
Should be ready now for re-review.

2020-09-25 07:52 UTC, lukasgraf approved these changes
LGTM 👍

2020-09-25 12:04 UTC, merged