Improve groups and teams ordering
4teamwork/opengever.core pull request #6633
Opened 2020-09-11 11:26 UTC by elioschmutz

This PR makes the following changes:

- Fix changelog of the previous merged PR
- Order teams and groups case insensitive
- Group titles can be `null`. We use now the group_id as the fallback row for ordering. Otherwise, all groups without a title would be unordered at the end of the response.

Jira: https://4teamwork.atlassian.net/browse/PHX-40

Follow-UP of #6626 

## Checklist (Must have)

_Everything has to be done/checked. Checked but not present means the author deemed it unnecessary._

- [x] Changelog entry
- [x] Link to issue (Jira or GitHub) and backlink in issue (Jira)

## Checklist (if applicable)

_Only applicable should be left and checked._

- API change:
  - [ ] Documentation is updated
  - If breaking:
    - [ ] api-change label added
    - [ ] Scrum master is informed
- New functionality:
  - [ ] for `document` also works for `mail`
  - [ ] for `task` also works for `forwarding`
- Upgrade steps (changes in profile):
  - [ ] Make it deferrable if possible
  - [ ] Execute as much as possible conditionally
- DB-Schema migration
  - [ ] All changes on a model (columns, etc) are included in a DB-schema migration.
  - [ ] Constraint names are shorter than 30 characters (`Oracle`)
- [ ] Change could impact client installations, client policies need to be adapted
- New translations
  - [ ] All msg-strings are unicode
- Change in schema definition:
  - [ ] If `missing_value` is specified, then `default` has to be set to the same value

2020-09-11 11:35 UTC, njohner commented
@elioschmutz I'd leave the sorting case-sensitive for now, as we have an open story for that and if I understood @lukasgraf correctly, we could set it to case-insensitive correctly if we want to. (see https://4teamwork.atlassian.net/browse/GEVER-982)

2020-09-11 11:58 UTC, elioschmutz commented
@njohner ok, thanks. I updated the PR

2020-09-14 07:10 UTC, elioschmutz commented
@lukasgraf I also requested your review because you wanted to take a look on it as well...

2020-09-14 07:59 UTC, lukasgraf requested changes

2020-09-14 07:59 UTC, lukasgraf commented on docs/HISTORY.txt
> +- Order groups and teams in User serializer by title. [elioschmutz]
This CL entry only speaks of the serializer. It doesn't address the fact that the ordering for `assigned_groups` in the core `OGDSService` now has been changed.

2020-09-14 07:59 UTC, lukasgraf commented on opengever/ogds/models/service.py
> +        query = query.order_by(func.coalesce(Group.title, Group.groupid))
I'm about worried about compatibility with Oracle and performance for `COALESCE`. This will now `ORDER BY COALESCE(title, groupid)` every single time `assigned_groups` is used somewhere - which is a lot. And we definitely don't have an index over `COALESCE(group.title, group.groupid)` that could be used.

For example, just to test whether the user is in the OrgUnit's `users_group`, which happens all the time, we definitely don't need this ordering. Is it really necessary to even do this sorting unconditionally at such a low level (inside the service)?

Either way, could you please test:
- that this works (functionally) on Oracle
- if there is a performance difference to the previous query on systems with large amounts of groups (for both PostgreSQL and Oracle)

2020-09-14 08:39 UTC, elioschmutz commented on opengever/ogds/models/service.py
> +        query = query.order_by(func.coalesce(Group.title, Group.groupid))
Postgres (~4500 groups, sg):
- without ordering: ~2.5ms
- order by title: ~8-10ms
- COALESCE: ~25-50ms

2020-09-14 10:13 UTC, lukasgraf commented on opengever/ogds/models/service.py
> +        query = query.order_by(func.coalesce(Group.title, Group.groupid))
Oracle (1168 Groups, ZG):

- without ordering: ~170ms
- order by title: ~175ms
- COALESCE: ~190ms

(Without filtering by user, but via SQLAlchemy ORM).

2020-09-14 13:10 UTC, lukasgraf approved these changes
LGTM 👍

2020-09-15 08:01 UTC, merged