Reuse already running solr instance if available
4teamwork/opengever.core pull request #6634
Opened 2020-09-11 11:50 UTC by elioschmutz

Currently, the `bin/testserver` will fail on startup if a solr is already running. So it's not possible to run a local dev environment in addition with a running testserver.

This PR updates the `testserver` script to check if there is already a running solr instance. if so, it will just reuse it. Otherwise, it will start a new solr instance.

2020-09-11 12:04 UTC, lukasgraf requested changes
Uhm, what? That would mean that *running tests* would possibly write to the Solr used for local development? Or possibly even a production (!) Solr that you have an SSH tunnel open to on `localhost:8983`.

2020-09-11 13:18 UTC, lukasgraf commented
@elioschmutz as discussed:
It's not quite as dangerous as I first feared, since the data is still separated into different solr cores inside the same instance (`development`, `testing` and `testserver`). But my uneasy feeling regarding `testserver` taking over control over a Solr instance it did not start itself remains.

The proper, long-term solution for this would IMHO be to separate the `testserver` Solr from the other ones at least by port, or even make it an entirely separate Solr instance. Only doing it by port doesn't seem to work (easily) because the Solr instance locks the cores on the filesystem, and prevents another instance accessing the same filesystem database from being started. And even though we only _use_ one specific core in the testserver, and an entirely different one for the development instance - Solr doesn't know that when booting, and needs to lock all the cores.

An intermediate solution could therefore be this:
Allow `bin/testserver` to reuse an already running Solr, but make it very explicit (instead of an automatism). Something like
`bin/testserver --reuse-running--solr=8983`. That could the testserver in a mode where it's given permission to _use_ that Solr, but shouldn't attempt to exercise any control over that process (don't attempt to start, and don't attempt to stop it when done).

2020-10-07 09:38 UTC, njohner commented
@elioschmutz what is the status here?

2020-10-07 09:44 UTC, elioschmutz commented
@njohner it's a draft PR again.
I had no time to update it. But I saw, that it's not easy to extend the bin/testserver script with additional arguments...

2020-10-07 11:07 UTC, jone commented
> Currently, the bin/testserver will fail on startup if a solr is already running. So it's not possible to run a local dev environment in addition with a running testserver.

@elioschmutz I think that is not true. The dev solr runs on `8983`, the testerver solr on `55003` by default.
You probably ran multiple testserver instances in parallel. You'd have to change the ports (e.g. through `SOLR_PORT`) when you do that.

2020-10-07 14:34 UTC, elioschmutz commented
> > Currently, the bin/testserver will fail on startup if a solr is already running. So it's not possible to run a local dev environment in addition with a running testserver.
> 
> @elioschmutz I think that is not true. The dev solr runs on `8983`, the testerver solr on `55003` by default.
> You probably ran multiple testserver instances in parallel. You'd have to change the ports (e.g. through `SOLR_PORT`) when you do that.

Unfortunately no:

<img width="977" alt="Bildschirmfoto 2020-10-07 um 15 59 07" src="https://user-images.githubusercontent.com/557005/95341046-27384000-08b6-11eb-96d5-ff4d7ee8b6e6.png">

2020-10-08 06:58 UTC, jone commented
@elioschmutz you seem to have the `SOLR_PORT` environment variable configured in your shell. This has the effect that you override the port for both, dev and testserver, with the same value. That's why you have this problem.
See `export | grep SOLR_PORT`.
You either need to unset the variable in your shell or you need to prefix each command (e.g. `SOLR_PORT=1234 bin/testserver`).

2020-10-12 07:19 UTC, elioschmutz commented
No... 
<img width="977" alt="Bildschirmfoto 2020-10-07 um 15 59 07" src="https://user-images.githubusercontent.com/557005/95716355-a4bfcf80-0c6b-11eb-8f0a-fb3840c933bb.png">

either something is completely wrong with my deployment or I missunderstand anything... but I can't get it run. The main solr is blocking all solr-cores on startup. So the testserver solr can't access the `testserver` core. See also the respons https://github.com/4teamwork/opengever.core/pull/6634#issuecomment-691090148

2020-10-12 07:26 UTC, jone commented
@elioschmutz `$SOLR_PORT` must not (!) be defined in your shell. Your screenshot shows that you have defined it, so your system is configured wrong 😉 

This is correct:

<img width="1424" alt="Bildschirmfoto 2020-10-12 um 09 26 00" src="https://user-images.githubusercontent.com/7469/95717262-f7e65200-0c6c-11eb-8e4b-e3e895c5b034.png">

2020-10-12 08:07 UTC, elioschmutz commented
No...

<img width="1069" alt="Bildschirmfoto 2020-10-12 um 10 06 29" src="https://user-images.githubusercontent.com/557005/95721281-a6d95c80-0c72-11eb-8021-80cd3c7655fb.png">

and no...

<img width="1059" alt="Bildschirmfoto 2020-10-12 um 10 06 36" src="https://user-images.githubusercontent.com/557005/95721296-aa6ce380-0c72-11eb-97ba-7c2520de1dba.png">

2020-10-12 13:56 UTC, jone commented
@elioschmutz you are right: I assumed that the problem is the shared port, but now I think that the problem is that the same data directory and lockfile is used.
I think that if you want to have two solrs running at the same time you either need two checkouts or two solr buildout parts (=two part directories, two war directories, two bin scripts)..

2020-10-12 14:01 UTC, elioschmutz commented
> @elioschmutz you are right: I assumed that the problem is the shared port, but now I think that the problem is that the same data directory and lockfile is used.
> I think that if you want to have two solrs running at the same time you either need two checkouts or two solr buildout parts (=two part directories, two war directories, two bin scripts)..

Yes, and thats exactly what I don't want 😉  I don't want to maintain two gever-checkouts all the time. I just wand to start my testserver beside of my gever if I need to. That was the reason why I opened this pr. It just reuses the already running solr.

In the end, I tried to extend the `bin/testserver` to accept some parameters as @lukasgraf suggested in his response. But I couldn't find a way how to pass additional arguments. Zope is in between and already consumes the arguments and will raise an error if there are not valid arguments.

2020-10-12 14:14 UTC, jone commented
> In the end, I tried to extend the `bin/testserver` to accept some parameters as @lukasgraf suggested in his response. But I couldn't find a way how to pass additional arguments. Zope is in between and already consumes the arguments and will raise an error if there are not valid arguments.

The argument parsing is part of the [robotframework server](https://github.com/plone/plone.app.robotframework/blob/master/src/plone/app/robotframework/server.py#L177).
I see two possible solutions:

1) copy the `server()` function into our code base and extend it. The challenge is then how to pass the information along.
2) use environment variables (e.g. `TESTSERVER_REUSE_RUNNING_SOLR=8983 bin/testserver`). You can easily read that in the solr testing layer code.

Personally, I'd go for 2). But I'm not in charge here 😜

2020-10-12 14:19 UTC, elioschmutz commented
Thanks for your input @jone . I like the second solution as well... @lukasgraf what do you think? Would it be an acceptable solution for you as well?

2020-10-13 14:58 UTC, lukasgraf commented
Option 2) sounds good to me as well 👍

2020-10-14 07:28 UTC, lukasgraf approved these changes
LGTM 👍 

I fear it doesn't make the logic for selecting the Solr port under all the possible conditions any easier to understand, especially for someone new to the code, but I don't currently have a clear suggestion how to do it any better.

2020-10-14 07:29 UTC, merged