Implement new api endpoint @ogds-group-listing.
4teamwork/opengever.core pull request #6649
Opened 2020-09-29 14:06 UTC by elioschmutz

This PR implements the new `@ogds-group-listing` endpoint.

This endpoint is needed by the fronted to be able to list local groups in a management view.

Jira: https://4teamwork.atlassian.net/browse/NE-83

## Checklist (Must have)

_Everything has to be done/checked. Checked but not present means the author deemed it unnecessary._

- [x] Changelog entry
- [x] Link to issue (Jira or GitHub) and backlink in issue (Jira)

## Checklist (if applicable)

_Only applicable should be left and checked._

- API change:
  - [x] Documentation is updated
  - If breaking:
    - [x] api-change label added
    - [ ] #delivery channel notified about breaking change
    - [ ] Scrum master is informed
- New functionality:
  - [ ] for `document` also works for `mail`
  - [ ] for `task` also works for `forwarding`
- Upgrade steps (changes in profile):
  - [ ] Make it deferrable if possible
  - [ ] Execute as much as possible conditionally
- DB-Schema migration
  - [ ] All changes on a model (columns, etc) are included in a DB-schema migration.
  - [ ] Constraint names are shorter than 30 characters (`Oracle`)
- [ ] Change could impact client installations, client policies need to be adapted
- New translations
  - [ ] All msg-strings are unicode
- Change in schema definition:
  - [ ] If `missing_value` is specified, then `default` has to be set to the same value

2020-09-30 13:01 UTC, njohner requested changes
Looks good overall. Just had some minor comments and I'm not sure about the user serialization. Open for discussion

2020-10-01 07:28 UTC, elioschmutz commented on opengever/api/serializer.py
> +            user_items.append({
The problem here is, that we don't really have a plone user which we can serialize. looking up the user here would cost too much. That's the reason why i do it by hand.

About the `token`. Thats absolutely true. I thought I discussed this with you. It's the way how it is implemented for all other "user" related attributes. But I agree, this is absolutely not the right way. I think we really have to handle this in the frontend. Even that we have to always return the serialized user needs to be fixed as soon as possible (when not now) with a central actor lookup endpoint and frontend-side caching.

2020-10-01 07:37 UTC, elioschmutz commented on docs/public/dev-manual/api/listings.rst
> +Paremeter nicht implementiert, ``facets`` werden ebenfalls nicht unterstützt.
I just copied it from the `@ogds-user-listing` endpoint. But you're right. I removed it.

2020-10-01 07:40 UTC, elioschmutz commented on opengever/api/tests/test_ogdsgrouplisting.py
> +
👍

2020-10-01 08:54 UTC, elioschmutz commented on opengever/api/serializer.py
> +            user_items.append({
@njohner the story about fixing the lookup mess is here: https://4teamwork.atlassian.net/browse/CA-664

So I would say we merge this PR as it is. We have to make a breaking api change PR anyway for the `CA-664`. I'll list this PR in the story `CA-664` to make sure we don't forget to revert it.

Do you agree with that?

I updated the PR with all your other change requests. So could you take another look?

2020-10-01 09:20 UTC, njohner commented on opengever/api/serializer.py
> +            user_items.append({
Fine with me, thanks for creating the story.

2020-10-01 09:21 UTC, njohner approved these changes
LGTM, except that tests are failing ;-)

2020-10-01 19:01 UTC, merged