Add @participations endpoints for dossiers
4teamwork/opengever.core pull request #6653
Opened 2020-10-01 10:09 UTC by tinagerber

In this PR some changes are implemented:
- CRUD endpoints are implemented for dossier participations
- Previously it was possible to have several participations per participant. This is now prevented by not being able to create a participation for a user if the user already has a participation on the dossier.
- Since it is possible that multiple participations exist for users, all participations had to be migrated.
- Since participations can now be modified via the API endpoint, a journal entry must be created for the modification of a participation.

About the upgrade step: maybe it should be deferrable, because it goes over all dossiers. Also, the endpoints will not be used as long as the frontend part is not implemented. Probably it would make sense to use the same upgrade step in the issue https://4teamwork.atlassian.net/browse/CA-17, because it must also touch all dossiers.

Jira: https://4teamwork.atlassian.net/browse/NE-98

## Checklist (Must have)

_Everything has to be done/checked. Checked but not present means the author deemed it unnecessary._

- [x] Changelog entry
- [x] Link to issue (Jira or GitHub) and backlink in issue (Jira)

## Checklist (if applicable)

_Only applicable should be left and checked._

- Upgrade steps (changes in profile):
  - [ ] Make it deferrable if possible
  - [x] Execute as much as possible conditionally
- New translations
  - [x] All msg-strings are unicode

2020-10-01 17:10 UTC, njohner reviewed
I'm not done yet, but as I'll call it a night, here is the beginning of my review...

2020-10-01 17:10 UTC, njohner commented on opengever/api/dossier_participations.py
> +def get_sql_participant(participant_identifier):
This duplicates the code from the vocabulary. Why not user the vocabulary instead (https://github.com/4teamwork/opengever.core/blob/master/opengever/contact/sources.py#L16)? I do realise the vocabulary is broken (at least I think it got broken in https://github.com/4teamwork/opengever.core/commit/da5cf3a97ad34e08fcfcbafc2ae08306477fb5c0, more precisely here: https://github.com/4teamwork/opengever.core/blob/master/opengever/contact/sources.py#L52, a line that anyway makes no sense. But basically I think it should be cast to int for all types except for ogds_user, then it will work again)

2020-10-02 07:12 UTC, tinagerber commented on docs/public/dev-manual/api/dossier_participations.rst
> +Ein Beteiligter kann die Rollen Kenntnisnahme, Mitwirkung oder Schlusszeichnung haben. Mittels eines GET-Requests können alle Beteiligten eines Dossiers und ihre Rollen abgefragt werden.
Ah, I didn't know that.

2020-10-02 07:17 UTC, tinagerber commented on opengever/journal/configure.zcml
> +      for="opengever.dossier.behaviors.dossier.IDossierMarker
The subscribers for he events for creating and deleting a participation also took this marker, so I used this one too.

2020-10-02 08:04 UTC, njohner requested changes
Thanks for all the tests 🎉 ! Overall LGTM.

2020-10-02 08:04 UTC, njohner commented on opengever/api/tests/test_dossier_participations.py
> +        self.assertIn({
I think the DELETE tests would be more robust if you chacked either:
- `browser.open(u'{}/@participations/{}'.format(self.dossier.absolute_url(), self.participant_id) , methot='GET', headers=self.api_headers` and that it raises after deletion
- or tests `self.assertIn(self.participant_id, [item['participation_id'] for item in browser.json['items']])`
- or test the `items_count` of the GET response?
In it's current form, the test would pass if the `DELETE` had actually modified the `participant_title` attribute for example.

2020-10-02 08:41 UTC, tinagerber commented on opengever/api/dossier_participations.py
> +    return [{"token": term.token, "title": term.title} for term in vocabulary]
The titles are already translated. I can't use the vocabulary serializer, because it returns a batched result, so it is useless for our purposes. The term serializer also returns only the title, so I don't think it makes sense to use it. https://github.com/plone/plone.restapi/blob/e8b3e9ceee29041ef7159955fefea122359afc3d/src/plone/restapi/serializer/vocabularies.py#L95

2020-10-02 09:26 UTC, tinagerber commented on opengever/api/tests/test_dossier_participations.py
> +    def add_participation(self, context, participant_id, roles, browser):
I go here about the API, because otherwise I would have to copy the method I have already written for the API here. So I found it easier to use the already existing one.

2020-10-02 09:38 UTC, tinagerber commented on opengever/dossier/events.py
> +        self.participant = participant
For local consistency I leave it as it is.

2020-10-02 11:57 UTC, tinagerber commented
@njohner I have implemented most of your desired changes, can you review it again?

2020-10-02 13:08 UTC, njohner approved these changes
LGTM, except the upgrade step. Please ammend

2020-10-02 13:08 UTC, njohner commented on opengever/core/upgrades/20200925090651_migrate_participations/upgrade.py
> +            old_participations = handler.get_participations()
Most dossiers will not have any participations saved in the annotations, and we do not want to write an empty list in there for all 300'000 dossier of KAPO 😅 .

2020-10-02 14:20 UTC, merged