Add Cadwork mimetypes
4teamwork/opengever.core pull request #6656
Opened 2020-10-02 12:35 UTC by buchi

Register mimetypes for Cadwork in mimetypes registry and add them to the editable types of Office Connector.

These are not official IANA mimetypes.

JIRA: https://4teamwork.atlassian.net/browse/CA-974

## Checklist (Must have)

- [x] Changelog entry
- [x] Link to issue (Jira or GitHub) and backlink in issue (Jira)

2020-10-05 12:39 UTC, deiferni reviewed
Please test your upgrades before you request a review. This one references a field which no longer exists.

2020-10-05 12:40 UTC, deiferni requested changes
⬆️

2020-10-06 08:39 UTC, buchi commented
@deiferni Fixed upgrade step.

2020-10-06 08:41 UTC, deiferni approved these changes

2020-10-06 09:39 UTC, merged