Extend the workspace testing fixture.
4teamwork/opengever.core pull request #6684
Opened 2020-10-16 13:12 UTC by elioschmutz

This PR extends the workspace testing fixture with:

- an email within a workspace
- a document within a folder

2020-10-16 15:33 UTC, njohner requested changes
LGTM, I'd just like to see them registered. I hate objects in the fixture that one cannot access easily. I know it's for the frontend for now, but still.
Also they should appear in the README in the list of fixture objects no?

2020-10-16 15:33 UTC, njohner commented on opengever/testing/fixtures.py
> +        create(
Can you register it, maybe as `workspace_mail`

2020-10-16 15:33 UTC, njohner commented on opengever/testing/fixtures.py
> +        create(
This one too?

2020-10-16 17:57 UTC, elioschmutz commented on opengever/testing/fixtures.py
> +        create(
if you hate it, I'll update it 😄

2020-10-16 17:57 UTC, elioschmutz commented
readme updated. It was not required because the new objects have not been registered.

2020-10-19 05:50 UTC, njohner approved these changes
LGTM, thanks!

2020-10-19 11:23 UTC, merged