Deif/ca 1067 improve poliy generator dynamic defaults
4teamwork/opengever.core pull request #6730
Opened 2020-11-09 13:33 UTC by deiferni

With this PR we make another baby-step towards improving the policy generator a bit.

We add new defaults that can be guessed from previous input for the following questions:
- bumblebee app id
- ogds db name
- ldap ou
- administrator group

We also switch question order, and ask for admin unit id first to generate defaults from the technical admin unit identifier instead from of from the user visible abbreviation. The questions for which defaults are generated are also asking for technical identifier, so that IMO makes more sense.

Jira: https://4teamwork.atlassian.net/browse/CA-1107

## Checklist (Must have)

_Everything has to be done/checked. Checked but not present means the author deemed it unnecessary._

- [x] Changelog entry
- [x] Link to issue (Jira or GitHub) and backlink in issue (Jira)

2020-11-09 15:00 UTC, lukasgraf requested changes
To be honest, I'm not entirely convinced this is going in the right direction.

My initial approach (years ago) with the ordering of these questions and deriving identifiers from previous questions was to start with the highest fidelity one (the one that contains / retains the most information), and then derive further, "lossy" identifiers from it.

E.g.:
`Dürrenäsch` (highest fidelity, capitalisation and umlauts preserved) -> `duerrenaesch` (lowercased, transliteration applied. Non-reversible information loss).

2020-11-09 15:00 UTC, lukasgraf commented on opengever/policytemplates/hooks.py
> +        'deployment.ldap_ou': answer.capitalize(),
I'm sceptical of this.

This will suggest incorrect OUs with a high rate, which then just will be accepted and can easily lead to a mess that then needs to be fixed, because it needs to correspond to what the OU is *actually* called in LDAP.

For example, this would happily suggest incorrect OUs like `Kwl`, `Kgs`, `Bgbaetterkinden`, `Bistumbasel`, ...

2020-11-09 15:08 UTC, deiferni commented on opengever/policytemplates/hooks.py
> +        'deployment.ldap_ou': answer.capitalize(),
I went with it because IMO it would get it right 80% of the time, especially for SaaS where we are in direct control of the OU name and usually create it after or while the policy is generated. Also it is "just" a default which can be overridden by manual input. But i understand the potential fear of devs just turning the brain off and pressing enter 🙃 .

So omitting the OU default and leave it to the dev to fill it in would also work here if you're sceptical about this change. Would that work for you? Do you agree with the other two suggestions though?

2020-11-09 15:46 UTC, lukasgraf approved these changes

2020-11-10 15:24 UTC, deiferni commented
as discussed yesterday, amended. the OU default is out as we want to force devs to think about it.

2020-11-10 15:24 UTC, merged