Optimize OGDS Sync
4teamwork/opengever.core pull request #6738
Opened 2020-11-13 14:12 UTC by buchi

_PR-Description: should contain all the information necessary for an outsider to understand the change without looking at the code or the issue!_

- _Why the change is necessary_
- _What the goal of the change is_
- _How change is achieved (e.g. design decisions)_
- _The author should advertise and sell the change in the PR body_

_Screenshot: whenever useful, but only as a visual aid._

Definition of Done: https://4teamwork.atlassian.net/wiki/spaces/CHX4TW/pages/917562/

## Checklist (Must have)

_Everything has to be done/checked. Checked but not present means the author deemed it unnecessary._

- [ ] Changelog entry
- [ ] Link to issue (Jira or GitHub) and backlink in issue (Jira)

## Checklist (if applicable)

_Only applicable should be left and checked._

- API change:
  - [ ] Documentation is updated
  - If breaking:
    - [ ] api-change label added
    - [ ] #delivery channel notified about breaking change
    - [ ] Scrum master is informed
- New functionality:
  - [ ] for `document` also works for `mail`
  - [ ] for `task` also works for `forwarding`
- Upgrade steps (changes in profile):
  - [ ] Make it deferrable if possible
  - [ ] Execute as much as possible conditionally
- DB-Schema migration
  - [ ] All changes on a model (columns, etc) are included in a DB-schema migration.
  - [ ] Constraint names are shorter than 30 characters (`Oracle`)
- [ ] Change could impact client installations, client policies need to be adapted
- New translations
  - [ ] All msg-strings are unicode
- Change in schema definition:
  - [ ] If `missing_value` is specified, then `default` has to be set to the same value

2020-11-16 13:47 UTC, lukasgraf requested changes
LGTM overall. 👍 
Mostly minor stuff or just comments, but the one issue with case-sensitivity between matching references in `uniqueUsers` to user IDs needs to be adressed I think.

2020-11-16 13:47 UTC, lukasgraf commented on opengever/ogds/base/sync/ldap_util.py
> +        next_range = '%s;range=%s-*' % (name, end + 1)
Do I understand correctly how this works? A range query like `member:range=500-*` is still subject to server side limits (e.g. a max page size), but unless the exit condition for the recursion becomes true (no more results returned), another wildcard range query will be issued with the new offset. So essentially several "fetch more" operations with a server-determined page size.

2020-11-16 13:47 UTC, lukasgraf commented on opengever/ogds/base/sync/ogds_updater.py
> +        ldap_keys = set(ldap_objects.keys())
These set operations are also case-sensitive. It's quite hard for me to judge right now what the implications are of this, and how it worked before, but we need to watch out for this, especially in ZG.

2020-11-16 15:42 UTC, lukasgraf approved these changes

2020-11-17 08:54 UTC, buchi commented on opengever/ogds/base/sync/ogds_updater.py
> +                    user_info = ldap_users.get(user_dn)
Changed to case-insensitive lookup

2020-11-17 08:54 UTC, buchi commented on opengever/ogds/base/sync/ogds_updater.py
> +from sqlalchemy.sql.expression import true
Removed

2020-11-17 08:55 UTC, buchi commented on opengever/ogds/base/sync/ogds_updater.py
> +        deleted = ogds_keys - ldap_keys
Amended. No longer deactivate already deactivated users and groups.

2020-11-17 08:58 UTC, buchi commented on opengever/ogds/base/sync/ogds_updater.py
> +            diff = set(ldap_objects[key].items()) ^ set(ogds_objects[key].items())
I'm leaving it as-is. We can tackle this if it really pops up somewhere.

2020-11-17 09:02 UTC, buchi commented on opengever/ogds/base/sync/ldap_util.py
> +        next_range = '%s;range=%s-*' % (name, end + 1)
Correct. See also: https://docs.microsoft.com/de-de/previous-versions/windows/desktop/ldap/searching-using-range-retrieval#range-retrieval-results

2020-11-17 10:43 UTC, buchi commented on opengever/ogds/base/sync/ogds_updater.py
> +        ldap_keys = set(ldap_objects.keys())
Should work as expected. If there are any case changes of the userid or groupid its treated as a different user/group

2020-11-17 12:22 UTC, merged