Nj/ca 1221/lock documents copied to workspace
4teamwork/opengever.core pull request #6742
Opened 2020-11-17 16:26 UTC by njohner

_PR-Description: should contain all the information necessary for an outsider to understand the change without looking at the code or the issue!_

- _Why the change is necessary_
- _What the goal of the change is_
- _How change is achieved (e.g. design decisions)_
- _The author should advertise and sell the change in the PR body_

_Screenshot: whenever useful, but only as a visual aid._

Definition of Done: https://4teamwork.atlassian.net/wiki/spaces/CHX4TW/pages/917562/

## Checklist (Must have)

_Everything has to be done/checked. Checked but not present means the author deemed it unnecessary._

- [ ] Changelog entry
- [ ] Link to issue (Jira or GitHub) and backlink in issue (Jira)

## Checklist (if applicable)

_Only applicable should be left and checked._

- API change:
  - [ ] Documentation is updated
  - If breaking:
    - [ ] api-change label added
    - [ ] #delivery channel notified about breaking change
    - [ ] Scrum master is informed
- New functionality:
  - [ ] for `document` also works for `mail`
  - [ ] for `task` also works for `forwarding`
- Upgrade steps (changes in profile):
  - [ ] Make it deferrable if possible
  - [ ] Execute as much as possible conditionally
- DB-Schema migration
  - [ ] All changes on a model (columns, etc) are included in a DB-schema migration.
  - [ ] Constraint names are shorter than 30 characters (`Oracle`)
- [ ] Change could impact client installations, client policies need to be adapted
- New translations
  - [ ] All msg-strings are unicode
- Change in schema definition:
  - [ ] If `missing_value` is specified, then `default` has to be set to the same value

2020-11-18 13:36 UTC, lukasgraf requested changes

2020-11-18 14:04 UTC, lukasgraf commented
As discussed: Looks good overall, very clean and also easy to review! 👍  🎉 
Just those minor points regarding the exact messages, and two others:
- There don't seem to be tests that verify that the lock is actually effective (in preventing changes - via REST API, classic UI, OfficeConnector and OfficeOnline). Please check whether this actually falls into Plone's responsibility and is covered by Plone tests that we should be able to rely on, or possibly some of ours in the meeting code.

<details><summary>The <b>move action</b> currently seems to be allowed (offered) on a locked document, but fails when attempting to perform it <i>(expand for traceback)</i></summary>
<p>

```
Traceback (most recent call last):
  File "/Users/lukasgraf/Plone/eggs/Zope2-2.13.28-py2.7.egg/ZPublisher/Publish.py", line 138, in publish
    request, bind=1)
  File "/Users/lukasgraf/Plone/eggs/Zope2-2.13.28-py2.7.egg/ZPublisher/mapply.py", line 77, in mapply
    if debug is not None: return debug(object,args,context)
  File "/Users/lukasgraf/Plone/eggs/Zope2-2.13.28-py2.7.egg/ZPublisher/Publish.py", line 48, in call_object
    result=apply(object,args) # Type s to step into published object.
  File "/Users/lukasgraf/Plone/eggs/plone.z3cform-0.8.1-py2.7.egg/plone/z3cform/layout.py", line 66, in __call__
    self.update()
  File "/Users/lukasgraf/Plone/eggs/plone.z3cform-0.8.1-py2.7.egg/plone/z3cform/layout.py", line 50, in update
    self.form_instance.update()
  File "/Users/lukasgraf/Plone/eggs/z3c.form-3.2.11-py2.7.egg/z3c/form/form.py", line 228, in update
    self.actions.execute()
  File "/Users/lukasgraf/Plone/eggs/plone.app.z3cform-0.7.8-py2.7.egg/plone/app/z3cform/csrf.py", line 21, in execute
    super(AuthenticatedButtonActions, self).execute()
  File "/Users/lukasgraf/Plone/eggs/z3c.form-3.2.11-py2.7.egg/z3c/form/action.py", line 98, in execute
    result = handler()
  File "/Users/lukasgraf/Plone/eggs/z3c.form-3.2.11-py2.7.egg/z3c/form/button.py", line 315, in __call__
    return handler(self.form, self.action)
  File "/Users/lukasgraf/Plone/eggs/z3c.form-3.2.11-py2.7.egg/z3c/form/button.py", line 170, in __call__
    return self.func(form, action)
  File "/Users/lukasgraf/Plone/buildouts/opengever/og-linkeddocs/opengever/dossier/move_items.py", line 159, in handle_submit
    failed_resource_locked_objects, )
  File "/Users/lukasgraf/Plone/buildouts/opengever/og-linkeddocs/opengever/dossier/move_items.py", line 231, in create_statusmessages
    mapping={'item': failed_objects[0]})
IndexError: list index out of range
``` 

</p>
</details>

2020-11-18 16:02 UTC, lukasgraf commented on opengever/locking/locales/de/LC_MESSAGES/opengever.locking.po
> +msgstr "Das Dokument des Verknüpftem Teamraum kann dann immer zurückgeführt werden und als neue Version für dieses Dokument verwendet werden."
I've looked at this message in context, and there is indeed space for an explanatory message. I would suggest something like this:
`Änderungen, welche an diesem Dokument in GEVER vorgenommen werden, könnten durch ein Zurückführen des Dokuments aus Teamraum als neue Version überschrieben werden.`
But I could also see a much simpler message, and having a go at it in a second pass.

2020-11-18 16:02 UTC, lukasgraf approved these changes

2020-11-18 16:05 UTC, lukasgraf commented
Changed my review to "Approved" because we already discussed the review feedback in detail, and there's nothing fundamental blocking a merge, IMHO. I would probably tend towards ship it _after_ the upcoming release.

2020-11-20 12:20 UTC, njohner commented
@lukasgraf I've added tests for locked documents and fixed the behaviour for trashing and moving locked documents. Want to have another look?

2020-11-20 12:22 UTC, tinagerber commented
@njohner changelog entry is in wrong release section

2020-11-20 12:22 UTC, lukasgraf commented
@njohner Yep. If possible, I'd like to ship a hotfix before merging this one.

2020-11-20 12:44 UTC, lukasgraf approved these changes
LGTM! 👍 
Nice! I these tests and fixes actually cover quite a few paths that were already wonky before.

2020-11-20 16:04 UTC, merged