Add feature flag for todos.
4teamwork/opengever.core pull request #6761
Opened 2020-12-03 12:53 UTC by tinagerber

This PR adds a feature flag for todos. This allows us to enable and disable ToDos and ToDo lists. By default, this feature is enabled so that no additional update steps are required in the policies.
With the policy generator the feature can be enabled and disabled.

Jira: https://4teamwork.atlassian.net/browse/NE-163

## Checklist (Must have)

_Everything has to be done/checked. Checked but not present means the author deemed it unnecessary._

- [x] Changelog entry
- [x] Link to issue (Jira or GitHub) and backlink in issue (Jira)

## Checklist (if applicable)

_Only applicable should be left and checked._

- API change:
  - [x] Documentation is updated

2020-12-04 18:21 UTC, deiferni requested changes
I'd like to see a bit more testing here, e.g. also for api content creation. Apart from comments LGTM 👍.

2020-12-04 18:21 UTC, deiferni commented on opengever/workspace/__init__.py
> +    from opengever.workspace.interfaces import IToDoSettings
are you running into cyclic imports here? if not please move it up to module level.

2020-12-04 18:21 UTC, deiferni commented on opengever/base/configuration.py
> +        features['todo'] = api.portal.get_registry_record('is_feature_enabled', interface=IToDoSettings)
please rename this to `workspace_todo`, we don't have good namespacing but todo is a bit too general IMO.

2020-12-04 18:21 UTC, deiferni commented on opengever/core/upgrades/20201203113604_add_to_do_feature_flag/registry.xml
> +  <records interface="opengever.workspace.interfaces.IToDoSettings" />
please restrict this upgrade step to the field you have added. if more fields are added in later upgrades and they are all installed at the same time this might conflict.

2020-12-07 09:00 UTC, tinagerber commented
@deiferni I have made the desired changes. Can you rereview?

2020-12-07 09:45 UTC, deiferni approved these changes

2020-12-07 09:57 UTC, merged