The @sharing endpoint returns a batched result set if using the search param.
4teamwork/opengever.core pull request #6918
Opened 2021-02-26 10:47 UTC by elioschmutz

The default local-roles serializer returns all current local roles by default. If we pass a search-param, it will return all available entries which could possibly be added to the local roles. This result set can contain a lot of entries:

<img width="1006" alt="Bildschirmfoto 2021-02-26 um 09 57 41" src="https://user-images.githubusercontent.com/557005/109290165-8b3cb000-7827-11eb-8af3-2177b8e81631.png">

Currently, such a response will break the UI.

So this PR customizes the local-roles serializer to return a batched result-set if searching for entries but returns an unbatched result-set if just requesting the current local roles.

<img width="554" alt="Bildschirmfoto 2021-02-26 um 11 47 27" src="https://user-images.githubusercontent.com/557005/109290843-70b70680-7828-11eb-957c-a15ab0e3cf7b.png">

Jira: https://4teamwork.atlassian.net/browse/CA-1831

## Checklist (Must have)

_Everything has to be done/checked. Checked but not present means the author deemed it unnecessary._

- [ ] Changelog entry
- [ ] Link to issue (Jira or GitHub) and backlink in issue (Jira)

## Checklist (if applicable)

_Only applicable should be left and checked._

- API change:
  - [ ] Documentation is updated
  - [ ] API Changelog entry (see [guide](https://4teamwork.atlassian.net/wiki/spaces/4TEAM/pages/451248812/API+Changelog+Guidelines))
  - If breaking:
    - [ ] api-change label added
    - [ ] #delivery channel notified about breaking change
    - [ ] Scrum master is informed
- New functionality:
  - [ ] for `document` also works for `mail`
  - [ ] for `task` also works for `forwarding`
- Upgrade steps (changes in profile):
  - [ ] Make it deferrable if possible
  - [ ] Execute as much as possible conditionally
- DB-Schema migration
  - [ ] All changes on a model (columns, etc) are included in a DB-schema migration.
  - [ ] Constraint names are shorter than 30 characters (`Oracle`)
- [ ] Change could impact client installations, client policies need to be adapted
- New translations
  - [ ] All msg-strings are unicode
- Change in schema definition:
  - [ ] If `missing_value` is specified, then `default` has to be set to the same value

2021-02-26 14:49 UTC, lukasgraf requested changes

2021-02-26 14:49 UTC, lukasgraf commented on docs/HISTORY.txt
> +- The @sharing endpoint returns a batched result set if using the search param.  [elioschmutz]
I would phrase this as "... endpoint **now** returns ..." to make it clear what was the behavior before and after. (Same for API changelog).

_Change_ logs should describe a _change_, not a state. 😉

2021-02-26 14:49 UTC, lukasgraf commented on opengever/api/local_roles.py
> +            results['entries_total'] = batch.items_total
No - please do not invent a different batching parameter style!
It's `items`, and `items_total`, etc..., as documented in [our docs](https://docs.onegovgever.ch/dev-manual/api/batching/) and [upstream in plone.restapi](https://plonerestapi.readthedocs.io/en/latest/batching.html).

2021-02-26 15:00 UTC, lukasgraf commented
Also:
>  [x] Documentation is updated

Really? (Just a quick description and an internal link to our [batching docs](https://docs.onegovgever.ch/dev-manual/api/batching/) is enough)

2021-02-26 16:37 UTC, elioschmutz commented on opengever/api/local_roles.py
> +            results['entries_total'] = batch.items_total
The `local_roles` serializer uses the key `entries`. So I use `entries_total` which is the logical pendent for `entries`.

2021-02-26 18:36 UTC, lukasgraf commented on opengever/api/local_roles.py
> +            results['entries_total'] = batch.items_total
Yes, but while that may be a stylistic consideration, the batching protocol being the same has actual practical implications: In order for people to be able to write reusable pagination implementations in their clients, we must use the same protocol everywhere. How else could a batching iterator like [`batchingService.js`](https://github.com/4teamwork/gever-ui/blob/master/src/batchingService.js) in gever-ui ever work? Or similar implementations in RIS / VM? 

If anything, the `entries` key is the odd one out here and should probably be renamed to `items`. If we're already making breaking changes to the `@sharing` endpoint, this would probably be as good a time as any to do it.

2021-03-01 14:52 UTC, elioschmutz commented on opengever/api/local_roles.py
> +            results['entries_total'] = batch.items_total
as discussed, I renamed `entries` to `items` and `entries_total` to `items_total` only if the `search` parameter is available.

2021-03-01 15:29 UTC, elioschmutz commented
@lukasgraf can you take a final look pls?

2021-03-01 20:26 UTC, lukasgraf approved these changes
LGTM, thanks! 👍

2021-03-01 21:10 UTC, merged