Properly reset the responsible watcher if a user accepts a task assigned to a team.
4teamwork/opengever.core pull request #6963
Opened 2021-04-06 15:34 UTC by elioschmutz

This PR properly handles watchers for team tasks accepted by a user.

With this change, if a user accepts a task assigned to a group, the group will be removed as a watcher of the resource and the user will be added. 

Jira: https://4teamwork.atlassian.net/browse/CA-1953

## Checklist

_Everything has to be done/checked. Checked but not present means the author deemed it unnecessary._

- [ ] Changelog entry
- [ ] Link to issue (Jira or GitHub) and backlink in issue (Jira)

_Only applicable should be left and checked._

- API change:
  - [ ] Documentation is updated
  - [ ] API Changelog entry (see [guide](https://4teamwork.atlassian.net/wiki/spaces/4TEAM/pages/451248812/API+Changelog+Guidelines))
  - If breaking:
    - [ ] api-change label added
    - [ ] #delivery channel notified about breaking change
    - [ ] Scrum master is informed
- New functionality:
  - [ ] for `document` also works for `mail`
  - [ ] for `task` also works for `forwarding`
- Further improvements needed:
  - [ ] Create follow-up stories and link them in the PR and Jira issue
- Upgrade steps (changes in profile):
  - [ ] Make it deferrable if possible
  - [ ] Execute as much as possible conditionally
- DB-Schema migration
  - [ ] All changes on a model (columns, etc) are included in a DB-schema migration.
  - [ ] Constraint names are shorter than 30 characters (`Oracle`)
- [ ] Change could impact client installations, client policies need to be adapted
- New translations
  - [ ] All msg-strings are unicode
- Change in schema definition:
  - [ ] If `missing_value` is specified, then `default` has to be set to the same value

2021-04-06 19:47 UTC, phgross requested changes

2021-04-06 19:47 UTC, phgross commented on opengever/task/tests/test_activities.py
> +        ogds_group = Group.query.get('projekt_a')
You query the group by its id to only get the id of the group --> ✂️

2021-04-06 19:47 UTC, phgross commented on opengever/task/transition.py
> +        import pdb; pdb.set_trace()
✂️  😉

2021-04-06 19:47 UTC, phgross commented on opengever/task/transition.py
> -        if self.context.is_team_task:
The reassign_team_task is no longer conditional, but I think it should be.

2021-04-08 12:37 UTC, elioschmutz commented
@phgross could you take another look?

2021-04-08 14:14 UTC, phgross approved these changes
👍

2021-04-09 14:09 UTC, merged