Add new @versions endpoint
4teamwork/opengever.core pull request #6974
Opened 2021-04-15 14:03 UTC by njohner

_PR-Description: should contain all the information necessary for an outsider to understand the change without looking at the code or the issue!_

- _Why the change is necessary_
- _What the goal of the change is_
- _How change is achieved (e.g. design decisions)_
- _The author should advertise and sell the change in the PR body_

_Screenshot: whenever useful, but only as a visual aid._

Definition of Done: https://4teamwork.atlassian.net/wiki/spaces/CHX4TW/pages/917562/

## Checklist

_Everything has to be done/checked. Checked but not present means the author deemed it unnecessary._

- [ ] Changelog entry
- [ ] Link to issue (Jira or GitHub) and backlink in issue (Jira)

_Only applicable should be left and checked._

- API change:
  - [ ] Documentation is updated
  - [ ] API Changelog entry (see [guide](https://4teamwork.atlassian.net/wiki/spaces/4TEAM/pages/451248812/API+Changelog+Guidelines))
  - If breaking:
    - [ ] api-change label added
    - [ ] #delivery channel notified about breaking change
    - [ ] Scrum master is informed
- New functionality:
  - [ ] for `document` also works for `mail`
  - [ ] for `task` also works for `forwarding`
- Further improvements needed:
  - [ ] Create follow-up stories and link them in the PR and Jira issue
- Upgrade steps (changes in profile):
  - [ ] Make it deferrable if possible
  - [ ] Execute as much as possible conditionally
- DB-Schema migration
  - [ ] All changes on a model (columns, etc) are included in a DB-schema migration.
  - [ ] Constraint names are shorter than 30 characters (`Oracle`)
- [ ] Change could impact client installations, client policies need to be adapted
- New translations
  - [ ] All msg-strings are unicode
- Change in schema definition:
  - [ ] If `missing_value` is specified, then `default` has to be set to the same value

2021-04-20 08:54 UTC, lukasgraf requested changes
I have some doubts that this is actually lazy. Batched, yes, but not lazy.

In the classic UI we introduced our own [`LazyHistoryMetadataProxy`](https://github.com/4teamwork/opengever.core/blob/master/opengever/document/browser/versions_tab.py#L177) (years ago) to make sure the table in the versions tab is actually lazy. Before, it was batched, but because of some stupid stuff the content history viewlet does, the entire history still was getting consumed even though we only displayed the first 25 results.

I believe the same thing might be happening here - `content_history_viewlet. fullHistory()` will call [`.revisionHistory()`](https://github.com/plone/plone.app.layout/blob/2.3.20/plone/app/layout/viewlets/content.py#L263-L319). And that will eventually fetch every version, via a [mapped `retrieve`](https://github.com/plone/plone.app.layout/blob/2.3.20/plone/app/layout/viewlets/content.py#L311-L317), even if it's not needed later.

If we're implementing our own `@versions` endpoint, couldn't we just reuse our `LazyHistoryMetadataProxy`?

2021-04-21 12:43 UTC, deiferni commented on opengever/api/history.py
> +        history = content_history_viewlet.revisionHistory()
you will benefit from https://github.com/4teamwork/opengever.core/pull/6981, too. But maybe also add a test to make sure that `@versions` also works when users only have `Reader`.

2021-04-21 15:59 UTC, njohner commented
Ok I've completely reworked that PR. We now use the lazy history, as suggested by @lukasgraf . @deif, to your comment, I've added a test, but note that the versions endpoint does not return an empty list for a reader, but instead it shows the version. That is also what we do in the classic UI, and I don't really see a problem with that?

2021-04-22 11:02 UTC, deiferni approved these changes
Please add an entry to changes. The api-changelog is updated, but i could not see the regular changelog entry.

LGTM 👍  otherwise!

2021-04-22 12:15 UTC, njohner commented on docs/public/dev-manual/api/versions.rst
> +                "@id": "http://example.org/ordnungssystem/dossier-23/document-123/@history/2",
Yeah you're right. Both return the same thing though :-D. But I changed it

2021-04-23 13:10 UTC, merged