Improve archival file conversion job management when resolving dossiers.
4teamwork/opengever.core pull request #6990
Opened 2021-04-27 15:46 UTC by njohner

To avoid swamping bumblebee with PDF conversion jobs when executing the `NightlyAfterResolveJobs`, we add a limit to the number of conversion jobs triggered by a deployment in one night.
Note that the `AfterResolveJobs.trigger_pdf_conversion` method was not very smart as it submitted conversion jobs for all documents in the dossier being resolved, but as dossier resolution is recursive, this happens for every subdossier too. We had already introduced a mechanism to at least [avoid sending several jobs for the same document in a single request](https://github.com/4teamwork/opengever.core/pull/5600), but this is not sufficient. Indeed it would still queue conversion jobs for documents from a previously resolved subdossier (which was not resolved in the same request). Also this will not work properly if the `AfterResolveJobs` for a large dossier and its subdossiers are handled over several nights by the nightly jobs. We therefore change `AfterResolveJobs.trigger_pdf_conversion` to only submit documents of the current dossier which are not contained in any of its subdossiers (so directly contained documents or contained in tasks or proposal that are in that dossier). This is much cleaner IMHO and allows us to set a limit to the number of conversion jobs queued to bumblebee in one night (not that we always send all documents for a given dossier / subdossier together, so that the limit is not a hard limit in the sense that it is only checked between jobs)

For https://4teamwork.atlassian.net/browse/CA-1871

## Checklist

_Everything has to be done/checked. Checked but not present means the author deemed it unnecessary._

- [x] Changelog entry
- [ ] Link to issue (Jira or GitHub) and backlink in issue (Jira)

2021-04-29 12:58 UTC, phgross requested changes
Looks good, besides the thing mentioned ...

2021-04-29 12:58 UTC, phgross commented on opengever/dossier/base.py
> +        documents = self.portal_catalog.unrestrictedSearchResults(
I would add a keyword argument `unrestricted` which is false by default, otherwise the method `get_contained_documents` gets reused and gets documents unrestricted by mistake.

2021-04-30 12:15 UTC, njohner commented
@phgross I've added one more commit to include the changes you requested. Can you have another look?

2021-04-30 12:17 UTC, phgross approved these changes
👍

2021-04-30 12:47 UTC, merged