Disable unwrapping of inbound mails.
4teamwork/opengever.core pull request #7044
Opened 2021-06-11 09:00 UTC by njohner

Unwrapping of inbound mails is rather confusing, notably when there are several attachments to an inbound mail, any of which being an E-mail, it will save that attachment into Gever instead of the whole E-mail. As this behavior is not necessary anymore we simply deactivate it for all deployments.

For https://4teamwork.atlassian.net/browse/CA-2375

## Checklist
- [x] Changelog entry
- [x] Link to issue (Jira or GitHub) and backlink in issue (Jira)
- Upgrade steps (changes in profile):
  - [ ] Make it deferrable if possible
  - [ ] Execute as much as possible conditionally

2021-06-11 09:36 UTC, phgross requested changes
Changes are looking good, but we should disable this setting also in the gever and teamraum policytemplates, because the setting is True by default.

2021-06-11 12:26 UTC, njohner commented
thanks for the feedback. Indeed I forgot the templates!

2021-06-15 06:49 UTC, phgross approved these changes
LGTM - just wonder if it works also for new teamraum policies

2021-06-15 06:49 UTC, phgross commented on opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/profiles/default/registry.xml.bob
> +  <records interface="ftw.mail.interfaces.IMailSettings">
Just wonder, is this file also included in teamraum policies?

2021-06-15 06:53 UTC, njohner commented on opengever/policytemplates/policy_template/opengever.+package.name+/opengever/+package.name+/+adminunit.id+/profiles/default/registry.xml.bob
> +  <records interface="ftw.mail.interfaces.IMailSettings">
yes.

2021-06-15 06:53 UTC, merged