Add support for nightly maintenance jobs
4teamwork/opengever.core pull request #7145
Opened 2021-08-27 07:39 UTC by njohner

With this PR we add a new nightly job provider for maintenance jobs. The implementation is meant to keep as much flexibility as possible, allowing to basically run any function in a nightly maintenance job. I also tried to make the queues efficient, using BTrees and only storing the strict minimum in the queues.

I also added a helper context manager that allows to easily use the nightly maintenance jobs for upgrades reindexing objects in the catalog or in solr.

Definition of Done: https://4teamwork.atlassian.net/wiki/spaces/CHX4TW/pages/917562/

For [CA-2366]

## Checklist

_Everything has to be done/checked. Checked but not present means the author deemed it unnecessary._

- [x] Changelog entry
- [x] Link to issue (Jira or GitHub) and backlink in issue (Jira)

[CA-2366]: https://4teamwork.atlassian.net/browse/CA-2366

2021-08-30 15:08 UTC, lukasgraf requested changes
LGTM! 👍 🎉 

Just those points as discussed.

2021-08-30 15:08 UTC, lukasgraf commented on opengever/core/upgrades/20210205084521_add_sortable_reference_number_index/upgrade.py
> +        with NightlyIndexer(idxs=["sortable_reference"],
(Really) small pointer to this usage example from README?

2021-08-31 08:54 UTC, njohner commented on opengever/nightlyjobs/maintenance_jobs.py
> +        module = importlib.import_module(module_dotted_name)
This led me to use the function's dotted name in the initialisation of a `MaintenanceJobType`

2021-09-06 11:49 UTC, njohner commented on opengever/core/upgrade.py
> +        manager.connection.commit(extract_after_commit=False)
Normally jobs are simply a dictionary and for maintenance jobs we have two problems to handle:
- Depending on the job type, we want to commit more or less frequently
- Depending on the job type, we also need to commit directly to solr (because when reindexing in solr only, we typically go directly over the handlers. Such changes do not get committed automatically).
In the end, the best way I found was to delegate committing to the providers. All existing providers will simply commit after each job. For the maintenance jobs, we store additional information for each queue, i.e. for each job type: commit frequency and whether to commit in solr. The provider can then decide for after each job whether it is time to commit and whether it should commit to solr.

2021-09-06 12:31 UTC, njohner commented
I've integrated all your suggestions. I've added everything in new commits (the last 10 commits).

2021-09-06 12:56 UTC, lukasgraf approved these changes
LGTM! 👍  🎉 
Very clean, I like it. Just some trivialities 😉 .

2021-09-06 12:56 UTC, lukasgraf commented on README.rst
> +This will register the corresponging jobs to the ``NightlyMaintenanceJobsProvider``.
corresponging 😜  🧽

2021-09-06 12:56 UTC, lukasgraf commented on opengever/nightlyjobs/maintenance_jobs.py
> +        self.job_counter = defaultdict(lambda: 0)
You just reinvented [`collections.Counter()`](https://docs.python.org/3/library/collections.html#collections.Counter) here, I think 😉

2021-09-06 12:56 UTC, lukasgraf commented on opengever/nightlyjobs/maintenance_jobs.py
> +    between commits, as well as the commit_to_solr flag which indicates the
`indicates the` -> `indicates`

2021-09-06 13:43 UTC, njohner commented on README.rst
> +This will register the corresponging jobs to the ``NightlyMaintenanceJobsProvider``.
🤣

2021-09-06 13:46 UTC, njohner commented on opengever/nightlyjobs/maintenance_jobs.py
> +        self.job_counter = defaultdict(lambda: 0)
👍

2021-09-06 14:48 UTC, merged