Implement sqlite isolation for e2e tests.
4teamwork/opengever.core pull request #7182
Opened 2021-09-17 15:37 UTC by elioschmutz

Isolation for the sqlite in e2e tests:

## before
https://user-images.githubusercontent.com/557005/133815478-4cbdee09-acb0-4c28-88c0-b3c4148da472.mov

## after
https://user-images.githubusercontent.com/557005/133815502-3e2cb4bd-2182-4d49-93ea-8f71bc178965.mov

2021-09-23 09:55 UTC, jone requested changes

2021-09-23 09:55 UTC, jone commented on opengever/core/testserver.py
> +# from z3c.saconfig import named_scoped_session
✂️

2021-09-23 09:55 UTC, jone commented on opengever/core/testserver.py
> +from ZODB.POSException import ConflictError
Müssen die Imports nicht sortiert werden?

2021-09-23 09:55 UTC, jone commented on opengever/core/testserver.py
> +            try:
Einrückung falsch

2021-09-23 09:55 UTC, jone commented on opengever/core/testserver.py
> +            except Exception as e:
Was für eine Exception wird hier gecatcht?

Ich verstehe das Problem hier noch zu wenig, was genau passiert. Wie kann ich das reproduzieren?
Dies schaut für mich nach einem Workaround aus, resp. wir verstehen es eben zu wenig. Wenn wir es besser verstehen können wir das vielleicht ohne catch-all verhindern.

Eine These ist dass wir ein Timing-Problem haben wie die Requests vom frontend her kommen, oder ein db-state-problem zwischen commit vom setup und requests auf der regulären DB connection. Am besten schauen wir das zusammen an.

2021-09-23 09:56 UTC, jone commented
@elioschmutz ich habe meinen PR #7187 rebased und bereinigt.

2021-09-24 15:55 UTC, jone approved these changes
Found some typos 🙈 , but other than that 👍 

For the record:
This isolation method is probably not very fast (we didn't measure it), but it is simple and works.

If we later need to make it faster, we can look into ideas such as:
- using the ftw.testing transaction interceptor here too; but we'd have to let the HTTP server be single threaded and reuse the same database connection without ever committing (this will be tricky)
- using pool of clean and prepared in-memory databases that we can switch and cleanup asynchronously (this will be tricky too)

Using PostgreSQL here is an option (we have a ancient branch somewhere), but it will not make the restore faster or easier.

2021-09-24 15:55 UTC, jone commented on opengever/core/testserver_selftest.py
> +                             'SQL issolation does not work properly.')
```suggestion
                             'SQL isolation does not work properly.')
```

2021-09-24 15:55 UTC, jone commented on opengever/core/testserver_selftest.py
> +            # beafore teardown/setup is properly removed.
```suggestion
            # beafore teardown/setup is properly removed.
```
```suggestion
            # before teardown/setup is properly removed.
```

2021-09-26 19:00 UTC, elioschmutz commented
I measured the speed of the sql-`isolate` method:

- The average speed of rolling back with this method based on 100 rollbacks is: `11ms`
- Currently, we have ~500 e2e tests. Means, the total time for rolling back the sql database when running all tests is: `5.5sec`.
- Running all tests in total takes in average: 35min on mclaren. The rollback of the sql-db would make 0.26% of the total running time.

I think this is fast enough and there is no need to improve the rollback-speed of the sql.

2021-09-27 06:57 UTC, jone commented
> * The average speed of rolling back with this method based on 100 rollbacks is: `11ms`

Cool! That's a lot faster than I expected! (I've mesured it years ago with a different approach, taking much longer).

2021-09-27 12:41 UTC, lukasgraf approved these changes
LGTM 👍, just a small request for clarification.

Welcome back from the dungeon, @elioschmutz and @jone 😜

2021-09-27 12:41 UTC, lukasgraf commented on opengever/core/testserver.py
> +            if 'CREATE TABLE' in line or \
Could you add a short comment here as to why these statements are skipped? Is the intent here to just skip DDL, and only back up DML?

2021-09-28 08:56 UTC, merged