Add flags to office connector url for attach action.
4teamwork/opengever.core pull request #7239
Opened 2021-11-09 14:35 UTC by tinagerber

⚠️  Requires new OfficeConnector version.

The flags are used to tell the OfficeConnector which things are not needed in the mail. The interpretation of the flags is done in the OfficeConnector.

For [CA-1815]

## Checklist

_Everything has to be done/checked. Checked but not present means the author deemed it unnecessary._

- [x] Changelog entry
- [x] Link to issue (Jira or GitHub) and backlink in issue (Jira)

2021-11-11 08:34 UTC, buchi requested changes
LGTM, but the parsing of the flags should be more robust. Either fallback to the default if bad data is provided or return a BadRequest response.

2021-11-11 08:34 UTC, buchi commented on opengever/officeconnector/helpers.py
> +        flags['attach'] = json.loads(request.form.get('attach', 'true'))
Parsing a boolean value with `json.loads()`  seems not appropriate to me. It's also easy to produce an error by providing an invalid value. I would use something like `request.form.get('attach', 'true').lower() in ['true', '1', 'yes', 'on']`

2021-11-11 08:34 UTC, buchi commented on opengever/officeconnector/helpers.py
> +        data = json.loads(request['BODY'])
Handle `ValueError` if body contains invalid data.

2021-11-11 08:34 UTC, buchi commented on opengever/officeconnector/helpers.py
> +            flag_list.append('-{}'.format(key))
you could use a list comprehension which seems more elegant to me, but this is just a personal preference:
`['-{}'.format(key) for key, value in flags.items() if not value]`

2021-11-11 16:04 UTC, tinagerber commented on opengever/officeconnector/helpers.py
> +        flags['attach'] = json.loads(request.form.get('attach', 'true'))
This would result in invalid data being classified as false, which is not the default. I now check the false values instead.

2021-11-11 16:05 UTC, tinagerber commented
@buchi parsing of the flags is now more robust, can you have another look?

2021-11-12 08:22 UTC, buchi commented on opengever/officeconnector/helpers.py
> +        data = json.loads(request['BODY'])
Hmm, I don't get your point. If there's invalid data in the body then `json.loads(request['BODY'])` will raise a `ValueError` which will result in a 500 server error. Thus I would catch the `ValueError`:
```python
try:
    data = json.loads(request['BODY'])
except ValueError:
    data = {}
```

2021-11-12 08:38 UTC, buchi approved these changes

2021-11-12 08:55 UTC, merged