Add a new feature to the '@config' endpiont: 'multiple_dossier_types'
4teamwork/opengever.core pull request #7319
Opened 2021-12-27 09:01 UTC by elioschmutz

This PR adds a new `feature` to the `@config` endpoint called: `multiple_dossier_types`

For [CA-2791]

## Checklist

_Everything has to be done/checked. Checked but not present means the author deemed it unnecessary._

- [x] Changelog entry
- [x] Link to issue (Jira or GitHub) and backlink in issue (Jira)

_Only applicable should be left and checked._

- API change:
  - [ ] Documentation is updated
  - [x] API Changelog entry (see [guide](https://4teamwork.atlassian.net/wiki/spaces/4TEAM/pages/451248812/API+Changelog+Guidelines))
  - If breaking:
    - [ ] api-change label added
    - [ ] #delivery channel notified about breaking change
    - [ ] Scrum master is informed
- New functionality:
  - [ ] for `document` also works for `mail`
  - [ ] for `task` also works for `forwarding`
- Further improvements needed:
  - [ ] Create follow-up stories and link them in the PR and Jira issue
- Upgrade steps (changes in profile):
  - [ ] Make it deferrable if possible
  - [ ] Execute as much as possible conditionally
- DB-Schema migration
  - [ ] All changes on a model (columns, etc) are included in a DB-schema migration.
  - [ ] Constraint names are shorter than 30 characters (`Oracle`)
- [ ] Change could impact client installations, client policies need to be adapted
- New translations
  - [ ] All msg-strings are unicode
- Change in schema definition:
  - [ ] If `missing_value` is specified, then `default` has to be set to the same value

2021-12-28 10:25 UTC, buchi requested changes

2021-12-28 10:25 UTC, buchi commented on opengever/api/tests/test_config.py
> +from opengever.dossier.vocabularies import count_available_dossier_types
✂️ this import is unused.

2021-12-29 08:15 UTC, buchi approved these changes

2021-12-29 08:32 UTC, elioschmutz commented
I force-pushed again to change the commit-message to what you suggested in the readme

2021-12-29 08:52 UTC, merged