Improve upgrade memory
4teamwork/opengever.core pull request #7337
Opened 2022-01-18 14:19 UTC by njohner

_PR-Description: should contain all the information necessary for an outsider to understand the change without looking at the code or the issue!_

- _Why the change is necessary_
- _What the goal of the change is_
- _How change is achieved (e.g. design decisions)_
- _The author should advertise and sell the change in the PR body_

_Screenshot: whenever useful, but only as a visual aid._

Definition of Done: https://4teamwork.atlassian.net/wiki/spaces/CHX4TW/pages/917562/

For [CA-XXXX]

## Checklist

_Everything has to be done/checked. Checked but not present means the author deemed it unnecessary._

- [ ] Changelog entry
- [ ] Link to issue (Jira or GitHub) and backlink in issue (Jira)

_Only applicable should be left and checked._

- API change:
  - [ ] Documentation is updated
  - [ ] API Changelog entry (see [guide](https://4teamwork.atlassian.net/wiki/spaces/4TEAM/pages/451248812/API+Changelog+Guidelines))
  - If breaking:
    - [ ] api-change label added
    - [ ] #delivery channel notified about breaking change
    - [ ] Scrum master is informed
- New functionality:
  - [ ] for `document` also works for `mail`
  - [ ] for `task` also works for `forwarding`
- Further improvements needed:
  - [ ] Create follow-up stories and link them in the PR and Jira issue
- Upgrade steps (changes in profile):
  - [ ] Make it deferrable if possible
  - [ ] Execute as much as possible conditionally
- DB-Schema migration
  - [ ] All changes on a model (columns, etc) are included in a DB-schema migration.
  - [ ] Constraint names are shorter than 30 characters (`Oracle`)
- [ ] Change could impact client installations, client policies need to be adapted
- New translations
  - [ ] All msg-strings are unicode
- Change in schema definition:
  - [ ] If `missing_value` is specified, then `default` has to be set to the same value

2022-01-24 10:59 UTC, lukasgraf requested changes

2022-01-24 10:59 UTC, lukasgraf commented on opengever/core/upgrades/20211221135724_add_dossier_type_index/upgrade.py
> +                indexer.add_by_obj(brain)
💥 This fails with `TypeError: ('Could not adapt', <opengever.base.brain.TranslatedTitleBrain object at 0x116543ad0>, <InterfaceClass plone.uuid.interfaces.IUUID>)` on a deployment that is upgraded from a state before the `Index dossier_type in Solr` was executed.

2022-01-31 09:35 UTC, njohner commented on opengever/core/upgrades/20211221135724_add_dossier_type_index/upgrade.py
> +                indexer.add_by_obj(brain)
Sorry, had testsed several times and combinations, but did some last minute modifications and thought I'd make a final test after the review...
Anyway thanks for spotting this. I've tested again the migration as well as the upgrade steps after the changes. I think now everything works fine

2022-01-31 11:38 UTC, lukasgraf approved these changes
LGTM 👍

2022-01-31 12:55 UTC, merged