Add username, groupname and external_id columns
4teamwork/opengever.core pull request #7562
Opened 2022-09-09 07:28 UTC by tinagerber

I did not migrate `username`/`groupname` for LDAP users/groups, because I think the mapping should be in the OGDS sync service. 

For local groups I set `groupid` as `groupname`, next OGDS sync should set `groupname`. As long as `groupname` can't be edited, that should be enough.

Also I am not 100% convinced that `username` and `groupname` should be unique, could probably lead to problems as inactive users/groups stay in the DB.

For [CA-4567]

## Checklist

_Everything has to be done/checked. Checked but not present means the author deemed it unnecessary._

- [x] Changelog entry
- [x] Link to issue (Jira or GitHub) and backlink in issue (Jira)

_Only applicable should be left and checked._

- Upgrade-Steps:
  - [x] SQL Operations do not use imported model (see [docs](https://4teamwork.atlassian.net/wiki/spaces/4TEAM/pages/994344994/Upgrade-Steps))

2022-09-12 07:47 UTC, lukasgraf requested changes
> I did not migrate username/groupname for LDAP users/groups, because I think the mapping should be in the OGDS sync service.

I don't quite understand what you mean by that.

2022-09-12 07:47 UTC, lukasgraf commented on changes/CA-4567-2.feature
> +Add groupname and external_id columns to group model. [tinagerber]
Double changelog?

2022-09-12 07:47 UTC, lukasgraf commented on opengever/ogds/models/user.py
> +    username = Column(String(USER_ID_LENGTH), unique=True)
I think you're right, `username` shouldn't have a unique constraint. After all, that's exactly why we're doing this - the username isn't a reliable primary key for users, and may be re-used for different accounts.

`external_id` should be unique however I think, at least at a given point in time.

2022-09-12 07:47 UTC, lukasgraf commented on opengever/ogds/models/user.py
> +    external_id = Column(String(USER_ID_LENGTH), unique=True)
Both `username` and `external_id` should be required (`nullable=False`). And as a consequence, everywhere where we create entries in the `users` or `groups` tables, we need to prefill `username` and `external_id` with whatever we write to `userid`. (Same for groups).

2022-09-12 08:44 UTC, tinagerber commented on changes/CA-4567-2.feature
> +Add groupname and external_id columns to group model. [tinagerber]
One is for the user model and the other for the group model 😄

2022-09-12 16:18 UTC, tinagerber commented
@lukasgraf As discussed, I did not set an index for username and groupname because you are implementing a case insensitive index. The failing test also fails in the nightlies and has nothing to do with this implementation.
Can you have another look?

2022-09-13 13:14 UTC, lukasgraf approved these changes
LGTM 👍

2022-09-13 15:01 UTC, buchi approved these changes

2022-09-13 16:22 UTC, merged