Extend the restriction of possible actions by guests
4teamwork/opengever.core pull request #7914
Opened 2024-03-21 09:57 UTC by KunzS85

Follow-up PR of: Add ability to restrict workspace mails and documents actions for guests #7909

For [CA-6417]

## Checklist

_Everything has to be done/checked. Checked but not present means the author deemed it unnecessary._

- [ ] Changelog entry
- [x] Link to issue (Jira or GitHub) and backlink in issue (Jira)

2024-03-21 13:35 UTC, lukasgraf requested changes
LGTM 👍 - just a small detail.

2024-03-21 13:35 UTC, lukasgraf commented on opengever/document/actions.py
> +        return (is_within_workspace(self.context)
I think this (`is_within_workspace(self.context)`) might also disable this action for documents in GEVER, where it _should_ be available.

So I think this should just be
```
def is_save_document_as_pdf_available(self):
        return not is_restricted_workspace_and_guest(self.context)
```

2024-03-21 14:21 UTC, elioschmutz reviewed
A guest should not have the `Copy or Move` permission, so I wonder why the action is visible for guests. And a guest should generally not be able to save a document as a pdf because he would not have enough permission to do that. 

So I think these actions should be disabled in general for a guest and not only for guests in restricted workspaces.

2024-03-22 07:06 UTC, KunzS85 commented on opengever/document/actions.py
> +        return (is_within_workspace(self.context)
At first i had it the way you suggest, but some tests failed. So i changed it to the current way. But I'll check it more closely.

2024-03-22 10:38 UTC, KunzS85 commented on opengever/document/actions.py
> +        return (is_within_workspace(self.context)
Due to the splitting of the issue, this method disappears from the class in this PR.

2024-03-22 11:30 UTC, KunzS85 commented
The general restriction for guests regarding Copy/Move/Save as PDF via permission has been moved to a new bug issue (CA-6855)

2024-03-25 08:33 UTC, buchi approved these changes

2024-03-25 08:33 UTC, buchi commented on changes/CA-6417.other
> +Hide some more actions for guest access on restricted workspaces [KunzS85]
The changelog entry could be more specific:
```suggestion
Hide "share content" and "zipexport" actions for guest access on restricted workspaces [KunzS85]
```

2024-04-03 07:13 UTC, merged