Bump ftw.contentstats to version 1.4.0
4teamwork/opengever.core pull request #7924
Opened 2024-04-04 12:11 UTC by buchi

Add support for Docker-based deployments.

## Checklist

- [x] Changelog entry
- [ ] Link to issue (Jira or GitHub) and backlink in issue (Jira)

2024-04-04 20:10 UTC, lukasgraf requested changes

2024-04-04 20:10 UTC, lukasgraf commented on docker/core/requirements-core.txt
> +scandir==1.10.0
I think`scandir` also needs to be pinned in `versions.cfg`, no? Otherwise we'll get an error because of "picked versions"  when running buildout in production. Or am I missing something here?

2024-04-05 10:12 UTC, buchi commented on docker/core/requirements-core.txt
> +scandir==1.10.0
👍🏻 added pinning in `versions.cfg`

2024-04-05 10:15 UTC, lukasgraf approved these changes

2024-04-05 11:34 UTC, merged