Improved repository root Excel export
4teamwork/opengever.core pull request #7945
Opened 2024-05-03 12:02 UTC by Abdu-moustafa

Improves the repository root Excel export feature by adding the folder UID and relative path to each entry
For [TI-131](https://4teamwork.atlassian.net/browse/TI-131)

**before**:

<img width="759" alt="before" src="https://github.com/4teamwork/opengever.core/assets/160112920/508e8e59-2ae9-4db6-9b2e-288e2ef69f6e">

**After**:
<img width="865" alt="after" src="https://github.com/4teamwork/opengever.core/assets/160112920/4e85035b-2ab7-4dfa-b9c3-4f93238b7fda">

## Checklist

_Everything has to be done/checked. Checked but not present means the author deemed it unnecessary._

- [x] Changelog entry
- [x] Link to issue (Jira or GitHub) and backlink in issue (Jira)

_Only applicable should be left and checked._

- Upgrade-Steps:
  - [ ] SQL Operations do not use imported model (see [docs](https://4teamwork.atlassian.net/wiki/spaces/4TEAM/pages/994344994/Upgrade-Steps))
  - [ ] Make it deferrable if possible
  - [ ] Execute as much as possible conditionally
  - DB-Schema migration
    - [ ] All changes on a model (columns, etc) are included in a DB-schema migration.
    - [ ] Constraint names are shorter than 30 characters (`Oracle`)
- API change:
  - [ ] Documentation is updated
  - [ ] API Changelog entry (see [guide](https://4teamwork.atlassian.net/wiki/spaces/4TEAM/pages/451248812/API+Changelog+Guidelines))
  - If breaking:
    - [ ] api-change label added
    - [ ] #delivery channel notified about breaking change
    - [ ] Scrum master is informed
- Bug fixed:
  - [ ] Resolved any Sentry issues caused by this bug
- New functionality:
  - [ ] for `document` also works for `mail`
  - [ ] for `task` also works for `forwarding`
- Further improvements needed:
  - [ ] Create follow-up stories and link them in the PR and Jira issue
- [ ] Change could impact client installations, client policies need to be adapted
- New translations
  - [ ] All msg-strings are unicode
- Change in schema definition:
  - [ ] If `missing_value` is specified, then `default` has to be set to the same value

2024-05-07 10:23 UTC, elioschmutz commented on opengever/repository/browser/excel_export.py
> +        return os.path.join("/", *self._repofolder.getPhysicalPath()[2:])
Use or overtake the `to_relative_path` function from [`opengever.core/opengever/base/solr/fields.py`](https://github.com/4teamwork/opengever.core/blob/master/opengever/base/solr/fields.py#L168)

`to_relative_path(self._repofolder.getPhysicalPath())`

2024-05-10 07:35 UTC, buchi requested changes
Just some objections regarding naming. Maybe have a look at https://peps.python.org/pep-0008/#naming-conventions

2024-05-10 07:35 UTC, buchi commented on opengever/repository/browser/excel_export.py
> +    label_repositoryfolder_UID = repository_translater(_(
naming should be lowercase with underscores.
```suggestion
    label_repositoryfolder_uid = repository_translater(_(
```

2024-05-10 07:35 UTC, buchi commented on opengever/repository/browser/excel_export.py
> +        {'id': 'get_folder_UID', 'title': label_repositoryfolder_UID, 'callable': True},
```suggestion
        {'id': 'get_folder_uid', 'title': label_repositoryfolder_uid, 'callable': True},
```

2024-05-10 07:35 UTC, buchi commented on opengever/repository/browser/excel_export.py
> +    def get_folder_UID(self):
```suggestion
    def get_folder_uid(self):
```

2024-05-10 08:01 UTC, buchi approved these changes

2024-05-10 08:02 UTC, merged