Fix Document date after drag and drop
4teamwork/opengever.core pull request #7971
Opened 2024-06-06 09:44 UTC by Abdu-moustafa

Fix Update document date on Drag & Drop from Outlook Mail

NOT FINISHED WAITING FOR [Detailierte Upload View](https://4teamwork.atlassian.net/browse/TI-331) due to refactoring

For [TI-458](https://4teamwork.atlassian.net/browse/TI-458)

## Checklist

- [x] Changelog entry
- [x] Link to issue (Jira or GitHub) and backlink in issue (Jira)

2024-06-20 08:30 UTC, elioschmutz requested changes
Please see the jira-comment from @phgross : https://4teamwork.atlassian.net/browse/TI-458?focusedCommentId=45534

The issue in this story is, that the document date for **mails** are not set properly. The TUS-Upload should use the Mail-Date as the document date, not the current date.

For testing: you should not adjust the existing test but add another test for mail to test if the correct date will be extracted.

2024-07-04 08:46 UTC, phgross requested changes

2024-07-04 08:46 UTC, phgross commented on opengever/api/tus.py
> +        from opengever.mail.mail import OGMail
imports do not belong here

2024-07-04 08:46 UTC, phgross commented on opengever/mail/tests/test_mail_metadata.py
> +    def test_initialize_metadata_sets_document_date(self):
I think this test would still pass without your fix, because the tus upload ist not used when creating via `create_mail`.

2024-07-04 08:49 UTC, phgross commented on changes/TI-458.other
> +Ensure the document date displays accurately after drag-and-drop actions. [amo]
It's not a display issue. 


```suggestion
Fix document_date when uploading mails with DnD, use mail header date. [amo]
```

2024-07-05 06:47 UTC, Abdu-moustafa commented on opengever/mail/tests/test_mail_metadata.py
> +    def test_initialize_metadata_sets_document_date(self):
i rremoved this test and provide a test on `test_tus.py`  `test_add_additional_metadata_for_ogmail` so we can test the `mail upload` via tus

2024-07-05 09:28 UTC, elioschmutz commented on changes/TI-458.other
> +Fix document_date when uploading mails with DnD, use mail header date. [amo]
the filename should be `.bugfix` not `.other`

2024-07-05 09:28 UTC, elioschmutz commented on opengever/api/tests/test_tus.py
> +        self.assertEqual(mail.document_date, uploaded_doc.document_date)
The test seems quite complicated and unrelated to your change.

Please, take a look at another test for documents: i.e.: `test_tus_upload_can_set_document_date` as as starting point and then adjust it.

In general, you need to upload a mail by tus and then check if the date is set correctly. To do this, you need to extend the `assert_tus_upload_succeeds`-method to allow another upload-data. Then you can pass `MAIL_DATA` from `from opengever.mail.tests import MAIL_DATA`.

The assert-statement should then validate, that the mail-header date will be used instead the metadata-date.

2024-07-11 07:54 UTC, phgross approved these changes
👍

2024-07-11 07:56 UTC, merged