Include group users in Teamraum participant Excel export
4teamwork/opengever.core pull request #7992
Opened 2024-07-10 06:49 UTC by Abdu-moustafa

This PR enhances the workspace participant Excel export feature by including users who are part of groups with permissions in the workspace. Previously, the export only listed users directly authorized in the workspace. With this update, the export will:

- Resolve group members and include users from these groups in the export.
- Ensure that no duplicated users in the export.

For [TI-669](https://4teamwork.atlassian.net/browse/TI-669)

## Checklist
- [x] Changelog entry
- [x] Link to issue (Jira or GitHub) and backlink in issue (Jira)

2024-07-10 13:51 UTC, phgross requested changes

2024-07-10 13:51 UTC, phgross commented on opengever/globalindex/browser/report.py
> +    def extract_user_ids(self, user_ids):
As dicussed this change should be in the `WorkspaceParticipantsReport` class

2024-07-11 07:47 UTC, phgross approved these changes
Just a small optimization possible otherwise LGTM 👍

2024-07-11 07:47 UTC, phgross commented on opengever/workspace/report.py
> +        for user_id in user_ids:
Imho you could avoid fetching the user twice, something like this

```
        user_ids = self.extract_user_ids_from_request()
        users = set()

        for user_id in user_ids:
            group_members = ogds_service().fetch_group(user_id)
            if group_members:
                users.update(group_members.users)
            else:
                user = [ogds_service().fetch_user(user_id)
                if user:
                    users.add(user)

        return list(users)
```

2024-07-12 08:36 UTC, elioschmutz approved these changes

2024-07-12 08:37 UTC, merged