Exclude inactive users and groups for non-managers in Sharing tab
4teamwork/opengever.core pull request #8000
Opened 2024-07-22 13:16 UTC by Abdu-moustafa

Update the `Sharing `endpoint with the following points :

1. In the sharing tab, inactive users and groups are displayed only for managers.
2. In edit mode, inactive users and groups are always displayed

For [TI-296](https://4teamwork.atlassian.net/browse/TI-296)

## Checklist

_Everything has to be done/checked. Checked but not present means the author deemed it unnecessary._

- [x] Changelog entry
- [x] Link to issue (Jira or GitHub) and backlink in issue (Jira)

2024-07-23 05:47 UTC, phgross requested changes
LGTM besides the test, in my opinion, they don't seem to be checking everything that has been changed.

2024-07-23 05:47 UTC, phgross commented on opengever/api/sharing.py
> +        """Disable `plone.DelegateRoles` permission check."""
and filter inactive groups and users

2024-07-23 05:47 UTC, phgross commented on opengever/api/sharing.py
> +            if self.extend_item_with_ogds_summary(item):
Why is there a new check here?

2024-07-23 05:47 UTC, phgross commented on opengever/sharing/tests/test_sharing.py
> +        manager.add_or_update(user_id, ['Reader'],
wrong indentation, please pyflake

2024-07-23 05:47 UTC, phgross commented on opengever/sharing/tests/test_sharing.py
> +    def test_only_manager_can_view_inactive_users_in_listing(self, browser):
your testing for inactive groups not users.

2024-07-23 05:47 UTC, phgross commented on opengever/sharing/tests/test_sharing.py
> +        self.assertItemsEqual(
What about inactive user? 🤔

2024-07-23 06:25 UTC, Abdu-moustafa commented on opengever/api/sharing.py
> +            if self.extend_item_with_ogds_summary(item):
As we use same logic for the lisitng and add Editing, i need some how to check if i can include the item or not via local boolean state.

2024-07-23 06:26 UTC, Abdu-moustafa commented on opengever/sharing/tests/test_sharing.py
> +    def test_only_manager_can_view_inactive_users_in_listing(self, browser):
I updated the test to test groups and users as well

2024-07-24 08:45 UTC, phgross approved these changes
:+1:

2024-07-24 09:12 UTC, merged