Provide context action to export dossier participations
4teamwork/opengever.core pull request #8009
Opened 2024-08-08 07:57 UTC by Abdu-moustafa

The PR provides an Excel export feature for dossier `participations` via `context action`.

For [TI-672](https://4teamwork.atlassian.net/browse/TI-672)

## Checklist
- [x] Changelog entry
- [x] Link to issue (Jira or GitHub) and backlink in issue (Jira)
- New translations
  - [x] All msg-strings are unicode

2024-08-12 07:36 UTC, phgross requested changes
Same here, I think you missunterstand the story:  
* There should be no need for an additional action, just the action should also be available on workspacefolders not just workspaces.

2024-08-14 13:20 UTC, Abdu-moustafa commented
> Same here, I think you missunterstand the story:
> 
> * There should be no need for an additional action, just the action should also be available on workspacefolders not just workspaces.

I use the same action on the workspacefolder

2024-08-14 14:19 UTC, phgross approved these changes

2024-08-14 14:19 UTC, phgross commented on changes/TI-672.other
> +Provide context action to export dossier participations. [amo]
Make workspace participation export action also available on workspace folders.

2024-08-15 05:59 UTC, merged