Add dossier_review_state solr index.
4teamwork/opengever.core pull request #8012
Opened 2024-08-14 13:04 UTC by elioschmutz

This PR implements the `dossier_review_state` index. The index provide the state of the current dossier or the closest parent dossier for other content types.

The use case for this index is to filter by contents within a dossier of a specific state. I.e. all documents within an inactive dossier.

For [TI-479]

## Checklist

- [x] Changelog entry
- [x] Link to issue (Jira or GitHub) and backlink in issue (Jira)

2024-08-21 11:34 UTC, lukasgraf requested changes
LGTM 👍 - just some minor details.

2024-08-21 11:34 UTC, lukasgraf commented on opengever/base/handlers.py
> +def update_dossier_review_state_event(obj, event):
Remove the `_event` from this method's name?

2024-08-21 11:34 UTC, lukasgraf commented on opengever/core/upgrades/20240814101526_add_dossier_review_state_index/upgrade.py
> +            IDexterityContent.__identifier__,
Can't we be more specific here? For example, do we really need to reindex repository roots and repository folders?

2024-08-21 11:34 UTC, lukasgraf commented on opengever/dossier/indexers.py
> +    while not ISiteRoot.providedBy(obj):
I would write this as `while obj and not ISiteRoot.providedBy(obj) :`

Otherwise an `None` object might lead to an infinite loop (`aq_parent` returns `None` for objects that aren't acquisition wrapped)

2024-08-28 06:52 UTC, elioschmutz commented
@lukasgraf could you take another look?

2024-08-28 13:19 UTC, lukasgraf approved these changes
LGTM! 👍

2024-08-28 13:35 UTC, merged