Resolve invitation error when user dose not exists any more
4teamwork/opengever.core pull request #8027
Opened 2024-08-28 12:00 UTC by Abdu-moustafa

This pull request addresses a recurring AttributeError encountered by users in Teamraum when handling invitations. The error was traced to an issue where a non-existent inviter was being referenced, leading to a failure in the invitation process.

For [TI-1036](https://4teamwork.atlassian.net/browse/TI-1036)

## Checklist

_Everything has to be done/checked. Checked but not present means the author deemed it unnecessary._

- [x] Changelog entry
- [x] Link to issue (Jira or GitHub) and backlink in issue (Jira)

2024-08-28 12:25 UTC, phgross requested changes
This is not the right way to fix this issues. 

The problem should be fixed by just using the Actor.lookup() instead of the `PloneUserActor` in the my-invitations view
.

2024-08-28 14:10 UTC, Abdu-moustafa commented
> This is not the right way to fix this issues.
> 
> The problem should be fixed by just using the Actor.lookup() instead of the `PloneUserActor` in the my-invitations view .

Move the logic to the `my-invitations`

2024-09-02 11:32 UTC, phgross requested changes

2024-09-02 11:32 UTC, phgross commented on opengever/workspace/tests/test_my_invitations.py
> +            # Resolve the inviter from the invitation
This test does not actually check whether the problem still exists or not. Instead of manually fetching the inviter and create the actor from it, you should call the my-invitations view with the test user.

2024-09-03 13:43 UTC, Abdu-moustafa commented on opengever/workspace/tests/test_my_invitations.py
> +            # Resolve the inviter from the invitation
✅

2024-09-04 07:35 UTC, lukasgraf approved these changes
LGTM 👍

2024-09-04 08:03 UTC, merged