Remove timeago scipt and implement absolute times
4teamwork/opengever.core pull request #8036
Opened 2024-09-05 08:54 UTC by Acrop146

Since we need to use `collective.js.timeago` from our fork, which isn’t released, it is one of only two source dependencies we have in production. This makes it a hassle to deploy, and also makes building docker images more complicated than it needs to be.

As the classical UI isn't in wide use, we can remove the relative time (and the package itself) and replace it with readable absolute time. Relative time is only used for "notifications" and "recently modified" tabs. Both have been reformatted in the backend to show legible absolute time. 

Before;

<img width="385" alt="1084_before" src="https://github.com/user-attachments/assets/7cbd3eec-41e2-432d-b7d5-f09694480ee3">

<img width="407" alt="1084_before2" src="https://github.com/user-attachments/assets/c9b64b54-54b6-49fa-8b17-acd0c8b14a00">

After:

<img width="408" alt="1084_after" src="https://github.com/user-attachments/assets/1fbd6cb2-521d-467c-bd5a-b2a231f38256">

<img width="358" alt="1084_after2" src="https://github.com/user-attachments/assets/08920398-f110-4b36-bf88-8a1a955fa26e">

For [TI-1084]

## Checklist

- [x] Changelog entry
- [x] Link to issue (Jira or GitHub) and backlink in issue (Jira)

- Upgrade-Steps:
  - [x] SQL Operations do not use imported model (see [docs](https://4teamwork.atlassian.net/wiki/spaces/4TEAM/pages/994344994/Upgrade-Steps))
  - [x] Execute as much as possible conditionally

[TI-1084]: https://4teamwork.atlassian.net/browse/TI-1084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-09-05 12:16 UTC, lukasgraf commented on opengever/activity/browser/views.py
> +                    pytz.UTC).strftime('%b %d, %Y %I:%M %p'),
I know you didn't request a review yet, but just as a heads up: I would rather use the format string `'%Y-%m-%d %H:%M'` here (purely numeric, 24h time), because otherwise we will produce a locale-dependent string that contains untranslated month names (and 12h time). Or rather translated, but in the (fixed) server locale, English. So it wouldn't be correctly translated for users with the UI set to German or French.

2024-09-09 08:10 UTC, Acrop146 commented on opengever/activity/browser/views.py
> +                    pytz.UTC).strftime('%b %d, %Y %I:%M %p'),
Done

2024-09-12 14:00 UTC, lukasgraf requested changes
Just a few minor things, otherwise looks good to me! 👍 

Great work! You even updated the `Dockerfile` and the GitHub action accordingly, even though I forgot to mention those in the JIRA issue! 🎉 👌

2024-09-16 07:04 UTC, Acrop146 commented on opengever/policy/base/upgrades/to4201.py
> -            'profile-collective.js.timeago:default')
Done!

2024-09-16 07:07 UTC, Acrop146 commented on opengever/core/upgrades/20240904131956_uninstall_time_ago/upgrade.py
> +        self.remove_broken_browserlayer('collective.js.timeago.interfaces', 'ILayer')
Done!

2024-09-16 07:07 UTC, Acrop146 commented on .github/workflows/docker-image.yml
>            repository: 4teamwork/opengever.maintenance
Done!

2024-09-18 14:57 UTC, lukasgraf approved these changes

2024-09-18 15:16 UTC, merged