Makes reports available for teamraum
4teamwork/opengever.core pull request #8042
Opened 2024-09-16 07:47 UTC by XenoY

Currently there is no overview of all permissions for a user or a group in Teamraum. This already exists in GEVER. We need to allow access for teamraum to the corresponding sources. We splitted the role mapping for the titles inside the report for GEVER and Teamraum.

_Needs changes from gever-ui:_

For [TI-115](https://4teamwork.atlassian.net/browse/TI-115)

## Checklist

_Everything has to be done/checked. Checked but not present means the author deemed it unnecessary._

- [x] Changelog entry
- [x] Link to issue (Jira or GitHub) and backlink in issue (Jira)
- New translations
  - [x] All msg-strings are unicode

2024-09-20 07:58 UTC, lukasgraf requested changes
LGTM, mostly! 👍 - but please double check with Elio, since he has just recently made made changes to the involved vocabularies/sources.

2024-09-20 07:58 UTC, lukasgraf commented on opengever/ogds/base/sources.py
> +    gever_only = False
I don't think these should be necessary any more after Elio's recent changes in https://github.com/4teamwork/opengever.core/pull/8045

(Those changes BTW are also the reason that there's merge conflicts. I would suggest that you maybe have a quick look with Elio again about this)

2024-09-20 07:58 UTC, lukasgraf commented on opengever/workspace/__init__.py
> +    'all_users_and_groups'
This doesn't really belong here, since this is a list of _types_ that are whitelisted, not vocabularies/sources. Which also means that it probably wasn't needed in the first place, because it didn't have any effect 😀

2024-09-23 07:57 UTC, XenoY commented on opengever/workspace/__init__.py
> +    'all_users_and_groups'
If i remove it, as it was before, i get an 404 on the `@globalsources/all_users_and_groups` request. Which is needed to select the user or group to make the report for. Maybe there is another place i can put it, but i think it is needed. 

`WHITELISTED_TEAMRAUM_PORTAL_TYPES` is referenced in https://github.com/4teamwork/opengever.core/blob/9a7e34fc9e434ca8baa5fa17df23c8ffa36c8331/opengever/api/schema/globalsources.py#L62-L65

![image](https://github.com/user-attachments/assets/bf7cf70f-c409-495a-b9f3-8596a508e9e8)
![image](https://github.com/user-attachments/assets/b0962bcd-528d-4989-b1c9-7fe2cb49afb5)

2024-09-23 08:05 UTC, lukasgraf commented on opengever/workspace/__init__.py
> +    'all_users_and_groups'
I see, you're right - it indeed acts as a list of sources. Sorry for the detour then, go ahead and keep it in 😉 👍

2024-09-23 08:59 UTC, elioschmutz commented
👍

2024-09-23 09:00 UTC, elioschmutz approved these changes

2024-09-23 10:23 UTC, merged