Ran/ti 21/teamraum document finalize
4teamwork/opengever.core pull request #8051
Opened 2024-09-23 15:47 UTC by Acrop146

Before: When a document was finalized in Gever and then copied to Teamroom, it lost its “finalized” status could be edited in the Teamroom. During upload back to Gever, a new version was created in the actually finalized document.

To fix this problem - a final state was created for Workspace documents (transitions not accessible to normal users). Additionally, overwriting a finalized Gever Document from Teamraum now throws an error.

For [TI-21]

## Checklist

- [x] Changelog entry
- [x] Link to issue (Jira or GitHub) and backlink in issue (Jira)

- Upgrade-Steps:

  - [x] Make it deferrable if possible
  - [x] Execute as much as possible conditionally

- New translations
  - [x] All msg-strings are unicode
- Change in schema definition:
  - [x] If `missing_value` is specified, then `default` has to be set to the same value

2024-09-24 12:16 UTC, elioschmutz requested changes
There seems to be a little mess with the commit order and commit content. Could you please update the PR and clean up the commits?

And please, use a meaningful PR instead of your nickname and jira-number. So i.e. `Introduce teamraum document final state`.

2024-09-24 12:16 UTC, elioschmutz commented on opengever/api/linked_workspaces.py
> +                  "currently checked out or Gever Document is finalized"))
generally, this the message-id which should not be the english translation... but it was already wrong.

2024-09-24 12:16 UTC, elioschmutz commented on opengever/workspaceclient/linked_workspaces.py
> +            raise CopyFromWorkspaceForbidden(
I'd use a new error for the different errors or use some kind of an exception attribute to differentiate it. After that, you can write more specific error messages for the user and there is no need of combining the messages.

2024-09-24 12:16 UTC, elioschmutz commented on changes/TI-21.feature
> +Add new workspace document state: opengever_workspace_document--STATUS--final" title="finalize. [ran]
✂️  ` title="finalize.`

2024-10-07 06:46 UTC, Acrop146 commented on opengever/workspaceclient/linked_workspaces.py
> +        document_metadata['final'] = document.is_final_document()
Yes, review state isnt present in "document_metadata" when I list it using "pp document_metadata

2024-10-07 07:11 UTC, Acrop146 commented on opengever/base/locales/de/LC_MESSAGES/plone.po
> -
Added to first commit

2024-10-07 07:31 UTC, Acrop146 commented on opengever/api/workspace.py
> +            self.obj.reindexObjectSecurity()
Implemented in "as_final_document" function.

2024-10-07 07:32 UTC, Acrop146 commented on opengever/api/linked_workspaces.py
> +                  "currently checked out or Gever Document is finalized"))
Understood!

2024-10-07 07:33 UTC, Acrop146 commented on opengever/core/lawgiver.zcml
> +  <lawgiver:map_permissions
Done, Lawgiver and all the resulting translations (when lawgiver is implemented) have been moved to first commit.

2024-10-07 07:33 UTC, Acrop146 commented on opengever/api/workspace.py
> +        super(UploadDocumentCopy, self).add_object_to_context()
Done, moved to first commit

2024-10-07 07:35 UTC, Acrop146 commented on opengever/api/tests/test_linked_workspaces.py
> +                             u"because it's currently checked out or Gever Document is finalized",
Done, squashed the commit into the first one.

2024-10-07 09:18 UTC, Acrop146 commented on opengever/workspaceclient/linked_workspaces.py
> +            raise CopyFromWorkspaceForbidden(
Done, implemented as new exception: GeverDocumentCantBeChanged

2024-10-07 10:02 UTC, elioschmutz approved these changes
👍 thanks! 

please see my comments before you merge

2024-10-07 10:02 UTC, elioschmutz commented on opengever/core/profiles/default/workflows/opengever_workspace_document/specification.txt
> +  A workspace admin can finalize.
is there a reason why we do restrict finalizing to admins only?

2024-10-07 10:51 UTC, Acrop146 commented on opengever/core/profiles/default/workflows/opengever_workspace_document/specification.txt
> +  A workspace admin can finalize.
Yes, the story mentioned that "normal users" shouldn't be able to transition the state of document

2024-10-07 11:06 UTC, Acrop146 commented on opengever/api/workspace.py
> +
Done

2024-10-07 11:06 UTC, Acrop146 commented on opengever/api/workspace.py
> +        if self.obj.portal_type == 'opengever.document.document' and data.get("final", None):
Implemented

2024-10-07 11:07 UTC, Acrop146 commented on opengever/document/document.py
> +            'review_state': self.final_state_workspace,
Implemented as:
`        if workflow_id == self.workspace_workflow_id:
            wftool.setStatusOf(workflow_id, self, {
            'review_state': self.final_state_workspace,
            'action': '',
            'actor': ''})
        else:
            wftool.setStatusOf(workflow_id, self, {
                'review_state': self.final_state,
                'action': '',
                'actor': ''})`

2024-10-07 11:19 UTC, Acrop146 commented on opengever/document/document.py
> +        return api.content.get_state(self) == self.final_state or api.content.get_state(self) == self.final_state_workspace
Done

2024-10-07 11:49 UTC, merged